[package]
name = "sillyfmt"
version = "0.1.0"
authors = ["Robert Ying <rbtying@aeturnalus.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
atty = "0.2.13"
lalrpop-util = "0.17.2"
regex = "0.2.1"

[build-dependencies]
lalrpop = "0.17.2"
