[package]
name = "sillyfmt-tree-sitter"
version = "0.1.0"
authors = ["Robert Ying <rbtying@aeturnalus.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
atty = "0.2.13"
sillyfmt = { path = '../sillyfmt' }
tree-sitter = "0.6.2"
regex = "0.2.1"

[build-dependencies]
cc = "1.0"
