#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 53
#define SYMBOL_COUNT 34
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3

enum {
  anon_sym_EQ_EQ_EQ = 1,
  anon_sym_LT_EQ_GT = 2,
  anon_sym_EQ_GT = 3,
  anon_sym_DASH_GT = 4,
  anon_sym_LT_EQ = 5,
  anon_sym_GT_EQ = 6,
  anon_sym_EQ_EQ = 7,
  anon_sym_EQ = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_COLON = 11,
  anon_sym_DASH = 12,
  anon_sym_PLUS = 13,
  anon_sym_LPAREN = 14,
  anon_sym_RPAREN = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  anon_sym_LBRACE = 18,
  anon_sym_RBRACE = 19,
  anon_sym_COMMA = 20,
  aux_sym_text_token1 = 21,
  sym_time = 22,
  sym_source_file = 23,
  sym__expression = 24,
  sym__nonseq_expr = 25,
  sym_binary_op = 26,
  sym_symbol = 27,
  sym_container = 28,
  sym_comma_delimited_sequence = 29,
  sym_text = 30,
  aux_sym_source_file_repeat1 = 31,
  aux_sym_comma_delimited_sequence_repeat1 = 32,
  aux_sym_comma_delimited_sequence_repeat2 = 33,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ_EQ_EQ] = "===",
  [anon_sym_LT_EQ_GT] = "<=>",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ] = "=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [aux_sym_text_token1] = "text_token1",
  [sym_time] = "time",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym__nonseq_expr] = "_nonseq_expr",
  [sym_binary_op] = "binary_op",
  [sym_symbol] = "symbol",
  [sym_container] = "container",
  [sym_comma_delimited_sequence] = "comma_delimited_sequence",
  [sym_text] = "text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comma_delimited_sequence_repeat1] = "comma_delimited_sequence_repeat1",
  [aux_sym_comma_delimited_sequence_repeat2] = "comma_delimited_sequence_repeat2",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [sym_time] = sym_time,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym__nonseq_expr] = sym__nonseq_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_symbol] = sym_symbol,
  [sym_container] = sym_container,
  [sym_comma_delimited_sequence] = sym_comma_delimited_sequence,
  [sym_text] = sym_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comma_delimited_sequence_repeat1] = aux_sym_comma_delimited_sequence_repeat1,
  [aux_sym_comma_delimited_sequence_repeat2] = aux_sym_comma_delimited_sequence_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__nonseq_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_container] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_delimited_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_delimited_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_delimited_sequence_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_close = 1,
  field_contents = 2,
  field_open = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_contents] = "contents",
  [field_open] = "open",
};

static const TSFieldMapSlice ts_field_map_slices[3] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 1},
    {field_open, 0},
  [2] =
    {field_close, 2},
    {field_contents, 1},
    {field_open, 0},
};

static TSSymbol ts_alias_sequences[3][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(19);
      if (lookahead == ')') ADVANCE(20);
      if (lookahead == '+') ADVANCE(18);
      if (lookahead == ',') ADVANCE(25);
      if (lookahead == '-') ADVANCE(17);
      if (lookahead == '2') ADVANCE(26);
      if (lookahead == ':') ADVANCE(16);
      if (lookahead == '<') ADVANCE(14);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '>') ADVANCE(15);
      if (lookahead == '[') ADVANCE(21);
      if (lookahead == ']') ADVANCE(22);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead == '}') ADVANCE(24);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(3);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(4);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(30);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(7);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '=') ADVANCE(6);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(12);
      if (lookahead == '>') ADVANCE(8);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(10);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != '<' &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ':' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ':' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(2);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_text_token1] = ACTIONS(1),
    [sym_time] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(53),
    [sym__expression] = STATE(5),
    [sym__nonseq_expr] = STATE(46),
    [sym_binary_op] = STATE(46),
    [sym_symbol] = STATE(46),
    [sym_container] = STATE(46),
    [sym_comma_delimited_sequence] = STATE(5),
    [sym_text] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ_GT] = ACTIONS(5),
    [anon_sym_EQ_GT] = ACTIONS(5),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [aux_sym_text_token1] = ACTIONS(17),
    [sym_time] = ACTIONS(19),
  },
  [2] = {
    [sym__expression] = STATE(21),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(21),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(27),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [3] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(41),
    [anon_sym_LT_EQ_GT] = ACTIONS(41),
    [anon_sym_EQ_GT] = ACTIONS(41),
    [anon_sym_DASH_GT] = ACTIONS(41),
    [anon_sym_LT_EQ] = ACTIONS(44),
    [anon_sym_GT_EQ] = ACTIONS(41),
    [anon_sym_EQ_EQ] = ACTIONS(44),
    [anon_sym_EQ] = ACTIONS(44),
    [anon_sym_LT] = ACTIONS(47),
    [anon_sym_GT] = ACTIONS(44),
    [anon_sym_COLON] = ACTIONS(41),
    [anon_sym_DASH] = ACTIONS(44),
    [anon_sym_PLUS] = ACTIONS(44),
    [anon_sym_LPAREN] = ACTIONS(50),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(55),
    [anon_sym_RBRACK] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(58),
    [anon_sym_RBRACE] = ACTIONS(53),
    [aux_sym_text_token1] = ACTIONS(61),
    [sym_time] = ACTIONS(64),
  },
  [4] = {
    [sym__expression] = STATE(22),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(22),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(22),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(31),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [5] = {
    [sym__expression] = STATE(17),
    [sym__nonseq_expr] = STATE(46),
    [sym_binary_op] = STATE(46),
    [sym_symbol] = STATE(46),
    [sym_container] = STATE(46),
    [sym_comma_delimited_sequence] = STATE(17),
    [sym_text] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ_GT] = ACTIONS(5),
    [anon_sym_EQ_GT] = ACTIONS(5),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [aux_sym_text_token1] = ACTIONS(17),
    [sym_time] = ACTIONS(19),
  },
  [6] = {
    [sym__expression] = STATE(14),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(14),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(14),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [7] = {
    [sym__expression] = STATE(15),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(15),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(15),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(71),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [8] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(73),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [9] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [10] = {
    [sym__expression] = STATE(8),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(8),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [11] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(73),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [12] = {
    [sym__expression] = STATE(11),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(11),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(75),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [13] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [14] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(77),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [15] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(77),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [16] = {
    [sym__expression] = STATE(9),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(9),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [17] = {
    [sym__expression] = STATE(17),
    [sym__nonseq_expr] = STATE(46),
    [sym_binary_op] = STATE(46),
    [sym_symbol] = STATE(46),
    [sym_container] = STATE(46),
    [sym_comma_delimited_sequence] = STATE(17),
    [sym_text] = STATE(46),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(79),
    [anon_sym_LT_EQ_GT] = ACTIONS(79),
    [anon_sym_EQ_GT] = ACTIONS(79),
    [anon_sym_DASH_GT] = ACTIONS(79),
    [anon_sym_LT_EQ] = ACTIONS(82),
    [anon_sym_GT_EQ] = ACTIONS(79),
    [anon_sym_EQ_EQ] = ACTIONS(82),
    [anon_sym_EQ] = ACTIONS(82),
    [anon_sym_LT] = ACTIONS(85),
    [anon_sym_GT] = ACTIONS(82),
    [anon_sym_COLON] = ACTIONS(79),
    [anon_sym_DASH] = ACTIONS(82),
    [anon_sym_PLUS] = ACTIONS(82),
    [anon_sym_LPAREN] = ACTIONS(88),
    [anon_sym_LBRACK] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(94),
    [aux_sym_text_token1] = ACTIONS(97),
    [sym_time] = ACTIONS(100),
  },
  [18] = {
    [sym__nonseq_expr] = STATE(33),
    [sym_binary_op] = STATE(33),
    [sym_symbol] = STATE(33),
    [sym_container] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(20),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_RBRACK] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(103),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(105),
  },
  [19] = {
    [sym__expression] = STATE(13),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(13),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(13),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(71),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [20] = {
    [sym__nonseq_expr] = STATE(33),
    [sym_binary_op] = STATE(33),
    [sym_symbol] = STATE(33),
    [sym_container] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(20),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(107),
    [anon_sym_LT_EQ_GT] = ACTIONS(107),
    [anon_sym_EQ_GT] = ACTIONS(107),
    [anon_sym_DASH_GT] = ACTIONS(107),
    [anon_sym_LT_EQ] = ACTIONS(110),
    [anon_sym_GT_EQ] = ACTIONS(107),
    [anon_sym_EQ_EQ] = ACTIONS(110),
    [anon_sym_EQ] = ACTIONS(110),
    [anon_sym_LT] = ACTIONS(113),
    [anon_sym_GT] = ACTIONS(110),
    [anon_sym_COLON] = ACTIONS(107),
    [anon_sym_DASH] = ACTIONS(110),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_LPAREN] = ACTIONS(116),
    [anon_sym_RPAREN] = ACTIONS(119),
    [anon_sym_LBRACK] = ACTIONS(121),
    [anon_sym_RBRACK] = ACTIONS(119),
    [anon_sym_LBRACE] = ACTIONS(124),
    [anon_sym_RBRACE] = ACTIONS(119),
    [anon_sym_COMMA] = ACTIONS(119),
    [aux_sym_text_token1] = ACTIONS(127),
    [sym_time] = ACTIONS(130),
  },
  [21] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(133),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [22] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(30),
    [sym_binary_op] = STATE(30),
    [sym_symbol] = STATE(30),
    [sym_container] = STATE(30),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(30),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(23),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(135),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(39),
  },
  [23] = {
    [sym__nonseq_expr] = STATE(33),
    [sym_binary_op] = STATE(33),
    [sym_symbol] = STATE(33),
    [sym_container] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(20),
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(34),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(137),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(105),
  },
  [24] = {
    [sym__nonseq_expr] = STATE(33),
    [sym_binary_op] = STATE(33),
    [sym_symbol] = STATE(33),
    [sym_container] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(20),
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(45),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [anon_sym_COMMA] = ACTIONS(139),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(105),
  },
  [25] = {
    [sym__nonseq_expr] = STATE(44),
    [sym_binary_op] = STATE(44),
    [sym_symbol] = STATE(44),
    [sym_container] = STATE(44),
    [sym_text] = STATE(44),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(119),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(141),
    [anon_sym_LT_EQ_GT] = ACTIONS(141),
    [anon_sym_EQ_GT] = ACTIONS(141),
    [anon_sym_DASH_GT] = ACTIONS(141),
    [anon_sym_LT_EQ] = ACTIONS(144),
    [anon_sym_GT_EQ] = ACTIONS(141),
    [anon_sym_EQ_EQ] = ACTIONS(144),
    [anon_sym_EQ] = ACTIONS(144),
    [anon_sym_LT] = ACTIONS(147),
    [anon_sym_GT] = ACTIONS(144),
    [anon_sym_COLON] = ACTIONS(141),
    [anon_sym_DASH] = ACTIONS(144),
    [anon_sym_PLUS] = ACTIONS(144),
    [anon_sym_LPAREN] = ACTIONS(150),
    [anon_sym_LBRACK] = ACTIONS(153),
    [anon_sym_LBRACE] = ACTIONS(156),
    [anon_sym_COMMA] = ACTIONS(119),
    [aux_sym_text_token1] = ACTIONS(159),
    [sym_time] = ACTIONS(162),
  },
  [26] = {
    [sym__nonseq_expr] = STATE(44),
    [sym_binary_op] = STATE(44),
    [sym_symbol] = STATE(44),
    [sym_container] = STATE(44),
    [sym_text] = STATE(44),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(103),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ_GT] = ACTIONS(5),
    [anon_sym_EQ_GT] = ACTIONS(5),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(103),
    [aux_sym_text_token1] = ACTIONS(17),
    [sym_time] = ACTIONS(165),
  },
  [27] = {
    [sym__nonseq_expr] = STATE(44),
    [sym_binary_op] = STATE(44),
    [sym_symbol] = STATE(44),
    [sym_container] = STATE(44),
    [sym_text] = STATE(44),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(26),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ_GT] = ACTIONS(5),
    [anon_sym_EQ_GT] = ACTIONS(5),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [aux_sym_text_token1] = ACTIONS(17),
    [sym_time] = ACTIONS(165),
  },
  [28] = {
    [sym__nonseq_expr] = STATE(33),
    [sym_binary_op] = STATE(33),
    [sym_symbol] = STATE(33),
    [sym_container] = STATE(33),
    [sym_text] = STATE(33),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(18),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(105),
  },
  [29] = {
    [sym__nonseq_expr] = STATE(42),
    [sym_binary_op] = STATE(42),
    [sym_symbol] = STATE(42),
    [sym_container] = STATE(42),
    [sym_text] = STATE(42),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(5),
    [anon_sym_LT_EQ_GT] = ACTIONS(5),
    [anon_sym_EQ_GT] = ACTIONS(5),
    [anon_sym_DASH_GT] = ACTIONS(5),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(5),
    [anon_sym_EQ_EQ] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(7),
    [anon_sym_COLON] = ACTIONS(5),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [anon_sym_LBRACE] = ACTIONS(15),
    [aux_sym_text_token1] = ACTIONS(17),
    [sym_time] = ACTIONS(167),
  },
  [30] = {
    [sym_symbol] = STATE(31),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_RPAREN] = ACTIONS(171),
    [anon_sym_LBRACK] = ACTIONS(169),
    [anon_sym_RBRACK] = ACTIONS(171),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_RBRACE] = ACTIONS(171),
    [anon_sym_COMMA] = ACTIONS(169),
    [aux_sym_text_token1] = ACTIONS(173),
    [sym_time] = ACTIONS(169),
  },
  [31] = {
    [sym__nonseq_expr] = STATE(35),
    [sym_binary_op] = STATE(35),
    [sym_symbol] = STATE(35),
    [sym_container] = STATE(35),
    [sym_text] = STATE(35),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(25),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(35),
    [aux_sym_text_token1] = ACTIONS(37),
    [sym_time] = ACTIONS(175),
  },
  [32] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(32),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(103),
    [anon_sym_LT_EQ_GT] = ACTIONS(103),
    [anon_sym_EQ_GT] = ACTIONS(103),
    [anon_sym_DASH_GT] = ACTIONS(103),
    [anon_sym_LT_EQ] = ACTIONS(177),
    [anon_sym_GT_EQ] = ACTIONS(103),
    [anon_sym_EQ_EQ] = ACTIONS(177),
    [anon_sym_EQ] = ACTIONS(177),
    [anon_sym_LT] = ACTIONS(177),
    [anon_sym_GT] = ACTIONS(177),
    [anon_sym_COLON] = ACTIONS(103),
    [anon_sym_DASH] = ACTIONS(177),
    [anon_sym_PLUS] = ACTIONS(177),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_RPAREN] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_RBRACK] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_RBRACE] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(179),
    [aux_sym_text_token1] = ACTIONS(177),
    [sym_time] = ACTIONS(103),
  },
  [33] = {
    [sym_symbol] = STATE(31),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_RPAREN] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(169),
    [anon_sym_RBRACK] = ACTIONS(169),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_RBRACE] = ACTIONS(169),
    [anon_sym_COMMA] = ACTIONS(169),
    [aux_sym_text_token1] = ACTIONS(173),
    [sym_time] = ACTIONS(169),
  },
  [34] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(32),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(182),
    [anon_sym_LT_EQ_GT] = ACTIONS(182),
    [anon_sym_EQ_GT] = ACTIONS(182),
    [anon_sym_DASH_GT] = ACTIONS(182),
    [anon_sym_LT_EQ] = ACTIONS(184),
    [anon_sym_GT_EQ] = ACTIONS(182),
    [anon_sym_EQ_EQ] = ACTIONS(184),
    [anon_sym_EQ] = ACTIONS(184),
    [anon_sym_LT] = ACTIONS(184),
    [anon_sym_GT] = ACTIONS(184),
    [anon_sym_COLON] = ACTIONS(182),
    [anon_sym_DASH] = ACTIONS(184),
    [anon_sym_PLUS] = ACTIONS(184),
    [anon_sym_LPAREN] = ACTIONS(182),
    [anon_sym_RPAREN] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(182),
    [anon_sym_RBRACK] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(182),
    [anon_sym_RBRACE] = ACTIONS(182),
    [anon_sym_COMMA] = ACTIONS(137),
    [aux_sym_text_token1] = ACTIONS(184),
    [sym_time] = ACTIONS(182),
  },
  [35] = {
    [sym_symbol] = STATE(31),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(186),
    [anon_sym_LT_EQ_GT] = ACTIONS(186),
    [anon_sym_EQ_GT] = ACTIONS(186),
    [anon_sym_DASH_GT] = ACTIONS(186),
    [anon_sym_LT_EQ] = ACTIONS(188),
    [anon_sym_GT_EQ] = ACTIONS(186),
    [anon_sym_EQ_EQ] = ACTIONS(188),
    [anon_sym_EQ] = ACTIONS(188),
    [anon_sym_LT] = ACTIONS(188),
    [anon_sym_GT] = ACTIONS(188),
    [anon_sym_COLON] = ACTIONS(186),
    [anon_sym_DASH] = ACTIONS(188),
    [anon_sym_PLUS] = ACTIONS(188),
    [anon_sym_LPAREN] = ACTIONS(186),
    [anon_sym_RPAREN] = ACTIONS(186),
    [anon_sym_LBRACK] = ACTIONS(186),
    [anon_sym_RBRACK] = ACTIONS(186),
    [anon_sym_LBRACE] = ACTIONS(186),
    [anon_sym_RBRACE] = ACTIONS(186),
    [anon_sym_COMMA] = ACTIONS(186),
    [aux_sym_text_token1] = ACTIONS(188),
    [sym_time] = ACTIONS(186),
  },
  [36] = {
    [anon_sym_EQ_EQ_EQ] = ACTIONS(31),
    [anon_sym_LT_EQ_GT] = ACTIONS(31),
    [anon_sym_EQ_GT] = ACTIONS(31),
    [anon_sym_DASH_GT] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(190),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(190),
    [anon_sym_EQ] = ACTIONS(190),
    [anon_sym_LT] = ACTIONS(190),
    [anon_sym_GT] = ACTIONS(190),
    [anon_sym_COLON] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(190),
    [anon_sym_PLUS] = ACTIONS(190),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [aux_sym_text_token1] = ACTIONS(190),
    [sym_time] = ACTIONS(31),
  },
  [37] = {
    [anon_sym_EQ_EQ_EQ] = ACTIONS(192),
    [anon_sym_LT_EQ_GT] = ACTIONS(192),
    [anon_sym_EQ_GT] = ACTIONS(192),
    [anon_sym_DASH_GT] = ACTIONS(192),
    [anon_sym_LT_EQ] = ACTIONS(194),
    [anon_sym_GT_EQ] = ACTIONS(192),
    [anon_sym_EQ_EQ] = ACTIONS(194),
    [anon_sym_EQ] = ACTIONS(194),
    [anon_sym_LT] = ACTIONS(194),
    [anon_sym_GT] = ACTIONS(194),
    [anon_sym_COLON] = ACTIONS(192),
    [anon_sym_DASH] = ACTIONS(194),
    [anon_sym_PLUS] = ACTIONS(194),
    [anon_sym_LPAREN] = ACTIONS(192),
    [anon_sym_RPAREN] = ACTIONS(192),
    [anon_sym_LBRACK] = ACTIONS(192),
    [anon_sym_RBRACK] = ACTIONS(192),
    [anon_sym_LBRACE] = ACTIONS(192),
    [anon_sym_RBRACE] = ACTIONS(192),
    [anon_sym_COMMA] = ACTIONS(192),
    [aux_sym_text_token1] = ACTIONS(194),
    [sym_time] = ACTIONS(192),
  },
  [38] = {
    [anon_sym_EQ_EQ_EQ] = ACTIONS(196),
    [anon_sym_LT_EQ_GT] = ACTIONS(196),
    [anon_sym_EQ_GT] = ACTIONS(196),
    [anon_sym_DASH_GT] = ACTIONS(196),
    [anon_sym_LT_EQ] = ACTIONS(198),
    [anon_sym_GT_EQ] = ACTIONS(196),
    [anon_sym_EQ_EQ] = ACTIONS(198),
    [anon_sym_EQ] = ACTIONS(198),
    [anon_sym_LT] = ACTIONS(198),
    [anon_sym_GT] = ACTIONS(198),
    [anon_sym_COLON] = ACTIONS(196),
    [anon_sym_DASH] = ACTIONS(198),
    [anon_sym_PLUS] = ACTIONS(198),
    [anon_sym_LPAREN] = ACTIONS(196),
    [anon_sym_RPAREN] = ACTIONS(196),
    [anon_sym_LBRACK] = ACTIONS(196),
    [anon_sym_RBRACK] = ACTIONS(196),
    [anon_sym_LBRACE] = ACTIONS(196),
    [anon_sym_RBRACE] = ACTIONS(196),
    [anon_sym_COMMA] = ACTIONS(196),
    [aux_sym_text_token1] = ACTIONS(198),
    [sym_time] = ACTIONS(196),
  },
  [39] = {
    [anon_sym_EQ_EQ_EQ] = ACTIONS(196),
    [anon_sym_LT_EQ_GT] = ACTIONS(196),
    [anon_sym_EQ_GT] = ACTIONS(196),
    [anon_sym_DASH_GT] = ACTIONS(196),
    [anon_sym_LT_EQ] = ACTIONS(198),
    [anon_sym_GT_EQ] = ACTIONS(196),
    [anon_sym_EQ_EQ] = ACTIONS(198),
    [anon_sym_EQ] = ACTIONS(198),
    [anon_sym_LT] = ACTIONS(198),
    [anon_sym_GT] = ACTIONS(198),
    [anon_sym_COLON] = ACTIONS(196),
    [anon_sym_DASH] = ACTIONS(198),
    [anon_sym_PLUS] = ACTIONS(198),
    [anon_sym_LPAREN] = ACTIONS(196),
    [anon_sym_RPAREN] = ACTIONS(196),
    [anon_sym_LBRACK] = ACTIONS(196),
    [anon_sym_RBRACK] = ACTIONS(196),
    [anon_sym_LBRACE] = ACTIONS(196),
    [anon_sym_RBRACE] = ACTIONS(196),
    [anon_sym_COMMA] = ACTIONS(196),
    [aux_sym_text_token1] = ACTIONS(198),
    [sym_time] = ACTIONS(196),
  },
  [40] = {
    [anon_sym_EQ_EQ_EQ] = ACTIONS(200),
    [anon_sym_LT_EQ_GT] = ACTIONS(200),
    [anon_sym_EQ_GT] = ACTIONS(200),
    [anon_sym_DASH_GT] = ACTIONS(200),
    [anon_sym_LT_EQ] = ACTIONS(202),
    [anon_sym_GT_EQ] = ACTIONS(200),
    [anon_sym_EQ_EQ] = ACTIONS(202),
    [anon_sym_EQ] = ACTIONS(202),
    [anon_sym_LT] = ACTIONS(202),
    [anon_sym_GT] = ACTIONS(202),
    [anon_sym_COLON] = ACTIONS(200),
    [anon_sym_DASH] = ACTIONS(202),
    [anon_sym_PLUS] = ACTIONS(202),
    [anon_sym_LPAREN] = ACTIONS(200),
    [anon_sym_RPAREN] = ACTIONS(200),
    [anon_sym_LBRACK] = ACTIONS(200),
    [anon_sym_RBRACK] = ACTIONS(200),
    [anon_sym_LBRACE] = ACTIONS(200),
    [anon_sym_RBRACE] = ACTIONS(200),
    [anon_sym_COMMA] = ACTIONS(200),
    [aux_sym_text_token1] = ACTIONS(202),
    [sym_time] = ACTIONS(200),
  },
  [41] = {
    [anon_sym_EQ_EQ_EQ] = ACTIONS(200),
    [anon_sym_LT_EQ_GT] = ACTIONS(200),
    [anon_sym_EQ_GT] = ACTIONS(200),
    [anon_sym_DASH_GT] = ACTIONS(200),
    [anon_sym_LT_EQ] = ACTIONS(202),
    [anon_sym_GT_EQ] = ACTIONS(200),
    [anon_sym_EQ_EQ] = ACTIONS(202),
    [anon_sym_EQ] = ACTIONS(202),
    [anon_sym_LT] = ACTIONS(202),
    [anon_sym_GT] = ACTIONS(202),
    [anon_sym_COLON] = ACTIONS(200),
    [anon_sym_DASH] = ACTIONS(202),
    [anon_sym_PLUS] = ACTIONS(202),
    [anon_sym_LPAREN] = ACTIONS(200),
    [anon_sym_RPAREN] = ACTIONS(200),
    [anon_sym_LBRACK] = ACTIONS(200),
    [anon_sym_RBRACK] = ACTIONS(200),
    [anon_sym_LBRACE] = ACTIONS(200),
    [anon_sym_RBRACE] = ACTIONS(200),
    [anon_sym_COMMA] = ACTIONS(200),
    [aux_sym_text_token1] = ACTIONS(202),
    [sym_time] = ACTIONS(200),
  },
  [42] = {
    [sym_symbol] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(186),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(186),
    [anon_sym_LT_EQ_GT] = ACTIONS(186),
    [anon_sym_EQ_GT] = ACTIONS(186),
    [anon_sym_DASH_GT] = ACTIONS(186),
    [anon_sym_LT_EQ] = ACTIONS(188),
    [anon_sym_GT_EQ] = ACTIONS(186),
    [anon_sym_EQ_EQ] = ACTIONS(188),
    [anon_sym_EQ] = ACTIONS(188),
    [anon_sym_LT] = ACTIONS(188),
    [anon_sym_GT] = ACTIONS(188),
    [anon_sym_COLON] = ACTIONS(186),
    [anon_sym_DASH] = ACTIONS(188),
    [anon_sym_PLUS] = ACTIONS(188),
    [anon_sym_LPAREN] = ACTIONS(186),
    [anon_sym_LBRACK] = ACTIONS(186),
    [anon_sym_LBRACE] = ACTIONS(186),
    [anon_sym_COMMA] = ACTIONS(186),
    [aux_sym_text_token1] = ACTIONS(188),
    [sym_time] = ACTIONS(186),
  },
  [43] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(103),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(103),
    [anon_sym_LT_EQ_GT] = ACTIONS(103),
    [anon_sym_EQ_GT] = ACTIONS(103),
    [anon_sym_DASH_GT] = ACTIONS(103),
    [anon_sym_LT_EQ] = ACTIONS(177),
    [anon_sym_GT_EQ] = ACTIONS(103),
    [anon_sym_EQ_EQ] = ACTIONS(177),
    [anon_sym_EQ] = ACTIONS(177),
    [anon_sym_LT] = ACTIONS(177),
    [anon_sym_GT] = ACTIONS(177),
    [anon_sym_COLON] = ACTIONS(103),
    [anon_sym_DASH] = ACTIONS(177),
    [anon_sym_PLUS] = ACTIONS(177),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_LBRACK] = ACTIONS(103),
    [anon_sym_LBRACE] = ACTIONS(103),
    [anon_sym_COMMA] = ACTIONS(204),
    [aux_sym_text_token1] = ACTIONS(177),
    [sym_time] = ACTIONS(103),
  },
  [44] = {
    [sym_symbol] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(169),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(169),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_COMMA] = ACTIONS(169),
    [aux_sym_text_token1] = ACTIONS(173),
    [sym_time] = ACTIONS(169),
  },
  [45] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(182),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(182),
    [anon_sym_LT_EQ_GT] = ACTIONS(182),
    [anon_sym_EQ_GT] = ACTIONS(182),
    [anon_sym_DASH_GT] = ACTIONS(182),
    [anon_sym_LT_EQ] = ACTIONS(184),
    [anon_sym_GT_EQ] = ACTIONS(182),
    [anon_sym_EQ_EQ] = ACTIONS(184),
    [anon_sym_EQ] = ACTIONS(184),
    [anon_sym_LT] = ACTIONS(184),
    [anon_sym_GT] = ACTIONS(184),
    [anon_sym_COLON] = ACTIONS(182),
    [anon_sym_DASH] = ACTIONS(184),
    [anon_sym_PLUS] = ACTIONS(184),
    [anon_sym_LPAREN] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(182),
    [anon_sym_COMMA] = ACTIONS(139),
    [aux_sym_text_token1] = ACTIONS(184),
    [sym_time] = ACTIONS(182),
  },
  [46] = {
    [sym_symbol] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(171),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(21),
    [anon_sym_LT_EQ_GT] = ACTIONS(21),
    [anon_sym_EQ_GT] = ACTIONS(21),
    [anon_sym_DASH_GT] = ACTIONS(21),
    [anon_sym_LT_EQ] = ACTIONS(23),
    [anon_sym_GT_EQ] = ACTIONS(21),
    [anon_sym_EQ_EQ] = ACTIONS(23),
    [anon_sym_EQ] = ACTIONS(23),
    [anon_sym_LT] = ACTIONS(23),
    [anon_sym_GT] = ACTIONS(23),
    [anon_sym_COLON] = ACTIONS(21),
    [anon_sym_DASH] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(169),
    [anon_sym_LBRACK] = ACTIONS(169),
    [anon_sym_LBRACE] = ACTIONS(169),
    [anon_sym_COMMA] = ACTIONS(169),
    [aux_sym_text_token1] = ACTIONS(173),
    [sym_time] = ACTIONS(169),
  },
  [47] = {
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(31),
    [anon_sym_LT_EQ_GT] = ACTIONS(31),
    [anon_sym_EQ_GT] = ACTIONS(31),
    [anon_sym_DASH_GT] = ACTIONS(31),
    [anon_sym_LT_EQ] = ACTIONS(190),
    [anon_sym_GT_EQ] = ACTIONS(31),
    [anon_sym_EQ_EQ] = ACTIONS(190),
    [anon_sym_EQ] = ACTIONS(190),
    [anon_sym_LT] = ACTIONS(190),
    [anon_sym_GT] = ACTIONS(190),
    [anon_sym_COLON] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(190),
    [anon_sym_PLUS] = ACTIONS(190),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_COMMA] = ACTIONS(31),
    [aux_sym_text_token1] = ACTIONS(190),
    [sym_time] = ACTIONS(31),
  },
  [48] = {
    [ts_builtin_sym_end] = ACTIONS(200),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(200),
    [anon_sym_LT_EQ_GT] = ACTIONS(200),
    [anon_sym_EQ_GT] = ACTIONS(200),
    [anon_sym_DASH_GT] = ACTIONS(200),
    [anon_sym_LT_EQ] = ACTIONS(202),
    [anon_sym_GT_EQ] = ACTIONS(200),
    [anon_sym_EQ_EQ] = ACTIONS(202),
    [anon_sym_EQ] = ACTIONS(202),
    [anon_sym_LT] = ACTIONS(202),
    [anon_sym_GT] = ACTIONS(202),
    [anon_sym_COLON] = ACTIONS(200),
    [anon_sym_DASH] = ACTIONS(202),
    [anon_sym_PLUS] = ACTIONS(202),
    [anon_sym_LPAREN] = ACTIONS(200),
    [anon_sym_LBRACK] = ACTIONS(200),
    [anon_sym_LBRACE] = ACTIONS(200),
    [anon_sym_COMMA] = ACTIONS(200),
    [aux_sym_text_token1] = ACTIONS(202),
    [sym_time] = ACTIONS(200),
  },
  [49] = {
    [ts_builtin_sym_end] = ACTIONS(200),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(200),
    [anon_sym_LT_EQ_GT] = ACTIONS(200),
    [anon_sym_EQ_GT] = ACTIONS(200),
    [anon_sym_DASH_GT] = ACTIONS(200),
    [anon_sym_LT_EQ] = ACTIONS(202),
    [anon_sym_GT_EQ] = ACTIONS(200),
    [anon_sym_EQ_EQ] = ACTIONS(202),
    [anon_sym_EQ] = ACTIONS(202),
    [anon_sym_LT] = ACTIONS(202),
    [anon_sym_GT] = ACTIONS(202),
    [anon_sym_COLON] = ACTIONS(200),
    [anon_sym_DASH] = ACTIONS(202),
    [anon_sym_PLUS] = ACTIONS(202),
    [anon_sym_LPAREN] = ACTIONS(200),
    [anon_sym_LBRACK] = ACTIONS(200),
    [anon_sym_LBRACE] = ACTIONS(200),
    [anon_sym_COMMA] = ACTIONS(200),
    [aux_sym_text_token1] = ACTIONS(202),
    [sym_time] = ACTIONS(200),
  },
  [50] = {
    [ts_builtin_sym_end] = ACTIONS(196),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(196),
    [anon_sym_LT_EQ_GT] = ACTIONS(196),
    [anon_sym_EQ_GT] = ACTIONS(196),
    [anon_sym_DASH_GT] = ACTIONS(196),
    [anon_sym_LT_EQ] = ACTIONS(198),
    [anon_sym_GT_EQ] = ACTIONS(196),
    [anon_sym_EQ_EQ] = ACTIONS(198),
    [anon_sym_EQ] = ACTIONS(198),
    [anon_sym_LT] = ACTIONS(198),
    [anon_sym_GT] = ACTIONS(198),
    [anon_sym_COLON] = ACTIONS(196),
    [anon_sym_DASH] = ACTIONS(198),
    [anon_sym_PLUS] = ACTIONS(198),
    [anon_sym_LPAREN] = ACTIONS(196),
    [anon_sym_LBRACK] = ACTIONS(196),
    [anon_sym_LBRACE] = ACTIONS(196),
    [anon_sym_COMMA] = ACTIONS(196),
    [aux_sym_text_token1] = ACTIONS(198),
    [sym_time] = ACTIONS(196),
  },
  [51] = {
    [ts_builtin_sym_end] = ACTIONS(196),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(196),
    [anon_sym_LT_EQ_GT] = ACTIONS(196),
    [anon_sym_EQ_GT] = ACTIONS(196),
    [anon_sym_DASH_GT] = ACTIONS(196),
    [anon_sym_LT_EQ] = ACTIONS(198),
    [anon_sym_GT_EQ] = ACTIONS(196),
    [anon_sym_EQ_EQ] = ACTIONS(198),
    [anon_sym_EQ] = ACTIONS(198),
    [anon_sym_LT] = ACTIONS(198),
    [anon_sym_GT] = ACTIONS(198),
    [anon_sym_COLON] = ACTIONS(196),
    [anon_sym_DASH] = ACTIONS(198),
    [anon_sym_PLUS] = ACTIONS(198),
    [anon_sym_LPAREN] = ACTIONS(196),
    [anon_sym_LBRACK] = ACTIONS(196),
    [anon_sym_LBRACE] = ACTIONS(196),
    [anon_sym_COMMA] = ACTIONS(196),
    [aux_sym_text_token1] = ACTIONS(198),
    [sym_time] = ACTIONS(196),
  },
  [52] = {
    [ts_builtin_sym_end] = ACTIONS(192),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(192),
    [anon_sym_LT_EQ_GT] = ACTIONS(192),
    [anon_sym_EQ_GT] = ACTIONS(192),
    [anon_sym_DASH_GT] = ACTIONS(192),
    [anon_sym_LT_EQ] = ACTIONS(194),
    [anon_sym_GT_EQ] = ACTIONS(192),
    [anon_sym_EQ_EQ] = ACTIONS(194),
    [anon_sym_EQ] = ACTIONS(194),
    [anon_sym_LT] = ACTIONS(194),
    [anon_sym_GT] = ACTIONS(194),
    [anon_sym_COLON] = ACTIONS(192),
    [anon_sym_DASH] = ACTIONS(194),
    [anon_sym_PLUS] = ACTIONS(194),
    [anon_sym_LPAREN] = ACTIONS(192),
    [anon_sym_LBRACK] = ACTIONS(192),
    [anon_sym_LBRACE] = ACTIONS(192),
    [anon_sym_COMMA] = ACTIONS(192),
    [aux_sym_text_token1] = ACTIONS(194),
    [sym_time] = ACTIONS(192),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(207), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(53)] = 0,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 0),
  [5] = {.count = 1, .reusable = true}, SHIFT(47),
  [7] = {.count = 1, .reusable = false}, SHIFT(47),
  [9] = {.count = 1, .reusable = false}, SHIFT(4),
  [11] = {.count = 1, .reusable = true}, SHIFT(19),
  [13] = {.count = 1, .reusable = true}, SHIFT(6),
  [15] = {.count = 1, .reusable = true}, SHIFT(7),
  [17] = {.count = 1, .reusable = false}, SHIFT(52),
  [19] = {.count = 1, .reusable = true}, SHIFT(46),
  [21] = {.count = 1, .reusable = true}, SHIFT(36),
  [23] = {.count = 1, .reusable = false}, SHIFT(36),
  [25] = {.count = 1, .reusable = false}, SHIFT(2),
  [27] = {.count = 1, .reusable = false}, SHIFT(38),
  [29] = {.count = 1, .reusable = true}, SHIFT(16),
  [31] = {.count = 1, .reusable = true}, REDUCE(sym_symbol, 1),
  [33] = {.count = 1, .reusable = true}, SHIFT(10),
  [35] = {.count = 1, .reusable = true}, SHIFT(12),
  [37] = {.count = 1, .reusable = false}, SHIFT(37),
  [39] = {.count = 1, .reusable = true}, SHIFT(30),
  [41] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [44] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [47] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [50] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(16),
  [53] = {.count = 1, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2),
  [55] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(10),
  [58] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(12),
  [61] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [64] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(30),
  [67] = {.count = 1, .reusable = false}, SHIFT(51),
  [69] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 1),
  [71] = {.count = 1, .reusable = true}, SHIFT(50),
  [73] = {.count = 1, .reusable = true}, SHIFT(41),
  [75] = {.count = 1, .reusable = true}, SHIFT(39),
  [77] = {.count = 1, .reusable = true}, SHIFT(48),
  [79] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [82] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(47),
  [85] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [88] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [91] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [94] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [97] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(52),
  [100] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [103] = {.count = 1, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2),
  [105] = {.count = 1, .reusable = true}, SHIFT(33),
  [107] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(36),
  [110] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(36),
  [113] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(2),
  [116] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(16),
  [119] = {.count = 1, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2),
  [121] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(10),
  [124] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(12),
  [127] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(37),
  [130] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(33),
  [133] = {.count = 1, .reusable = false}, SHIFT(40),
  [135] = {.count = 1, .reusable = false}, SHIFT(49),
  [137] = {.count = 1, .reusable = true}, SHIFT(28),
  [139] = {.count = 1, .reusable = true}, SHIFT(27),
  [141] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(47),
  [144] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(47),
  [147] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(4),
  [150] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(19),
  [153] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(6),
  [156] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(7),
  [159] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(52),
  [162] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(44),
  [165] = {.count = 1, .reusable = true}, SHIFT(44),
  [167] = {.count = 1, .reusable = true}, SHIFT(42),
  [169] = {.count = 1, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 1),
  [171] = {.count = 1, .reusable = true}, REDUCE(sym__expression, 1),
  [173] = {.count = 1, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 1),
  [175] = {.count = 1, .reusable = true}, SHIFT(35),
  [177] = {.count = 1, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2),
  [179] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2), SHIFT_REPEAT(28),
  [182] = {.count = 1, .reusable = true}, REDUCE(sym_comma_delimited_sequence, 2),
  [184] = {.count = 1, .reusable = false}, REDUCE(sym_comma_delimited_sequence, 2),
  [186] = {.count = 1, .reusable = true}, REDUCE(sym_binary_op, 3),
  [188] = {.count = 1, .reusable = false}, REDUCE(sym_binary_op, 3),
  [190] = {.count = 1, .reusable = false}, REDUCE(sym_symbol, 1),
  [192] = {.count = 1, .reusable = true}, REDUCE(sym_text, 1),
  [194] = {.count = 1, .reusable = false}, REDUCE(sym_text, 1),
  [196] = {.count = 1, .reusable = true}, REDUCE(sym_container, 2, .production_id = 1),
  [198] = {.count = 1, .reusable = false}, REDUCE(sym_container, 2, .production_id = 1),
  [200] = {.count = 1, .reusable = true}, REDUCE(sym_container, 3, .production_id = 2),
  [202] = {.count = 1, .reusable = false}, REDUCE(sym_container, 3, .production_id = 2),
  [204] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2), SHIFT_REPEAT(27),
  [207] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
};

#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_sillyfmt(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
