#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 64
#define LARGE_STATE_COUNT 63
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 1
#define TOKEN_COUNT 24
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3

enum {
  anon_sym_COLON_COLON = 1,
  anon_sym_EQ_EQ_EQ = 2,
  anon_sym_LT_EQ_GT = 3,
  anon_sym_EQ_GT = 4,
  anon_sym_DASH_GT = 5,
  anon_sym_LT_EQ = 6,
  anon_sym_GT_EQ = 7,
  anon_sym_EQ_EQ = 8,
  anon_sym_EQ = 9,
  anon_sym_COLON = 10,
  anon_sym_DASH = 11,
  anon_sym_PLUS = 12,
  anon_sym_LT = 13,
  anon_sym_GT = 14,
  anon_sym_LPAREN = 15,
  anon_sym_RPAREN = 16,
  anon_sym_LBRACK = 17,
  anon_sym_RBRACK = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_COMMA = 21,
  aux_sym_text_token1 = 22,
  sym_time = 23,
  sym_source_file = 24,
  sym__expression = 25,
  sym__nonseq_expr = 26,
  sym_binary_op = 27,
  sym_nonsymbol = 28,
  sym_symbol = 29,
  sym_conflicting_symbol = 30,
  sym_container = 31,
  sym_comma_delimited_sequence = 32,
  sym_text = 33,
  aux_sym_source_file_repeat1 = 34,
  aux_sym_comma_delimited_sequence_repeat1 = 35,
  aux_sym_comma_delimited_sequence_repeat2 = 36,
  anon_alias_sym_subbinary_op = 37,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON_COLON] = "::",
  [anon_sym_EQ_EQ_EQ] = "===",
  [anon_sym_LT_EQ_GT] = "<=>",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_EQ] = "=",
  [anon_sym_COLON] = ":",
  [anon_sym_DASH] = "-",
  [anon_sym_PLUS] = "+",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COMMA] = ",",
  [aux_sym_text_token1] = "text_token1",
  [sym_time] = "time",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym__nonseq_expr] = "_nonseq_expr",
  [sym_binary_op] = "binary_op",
  [sym_nonsymbol] = "nonsymbol",
  [sym_symbol] = "symbol",
  [sym_conflicting_symbol] = "conflicting_symbol",
  [sym_container] = "container",
  [sym_comma_delimited_sequence] = "comma_delimited_sequence",
  [sym_text] = "text",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comma_delimited_sequence_repeat1] = "comma_delimited_sequence_repeat1",
  [aux_sym_comma_delimited_sequence_repeat2] = "comma_delimited_sequence_repeat2",
  [anon_alias_sym_subbinary_op] = "subbinary_op",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON_COLON] = anon_sym_COLON_COLON,
  [anon_sym_EQ_EQ_EQ] = anon_sym_EQ_EQ_EQ,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [aux_sym_text_token1] = aux_sym_text_token1,
  [sym_time] = sym_time,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym__nonseq_expr] = sym__nonseq_expr,
  [sym_binary_op] = sym_binary_op,
  [sym_nonsymbol] = sym_nonsymbol,
  [sym_symbol] = sym_symbol,
  [sym_conflicting_symbol] = sym_conflicting_symbol,
  [sym_container] = sym_container,
  [sym_comma_delimited_sequence] = sym_comma_delimited_sequence,
  [sym_text] = sym_text,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comma_delimited_sequence_repeat1] = aux_sym_comma_delimited_sequence_repeat1,
  [aux_sym_comma_delimited_sequence_repeat2] = aux_sym_comma_delimited_sequence_repeat2,
  [anon_alias_sym_subbinary_op] = anon_alias_sym_subbinary_op,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_text_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__nonseq_expr] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_op] = {
    .visible = true,
    .named = true,
  },
  [sym_nonsymbol] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_conflicting_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_container] = {
    .visible = true,
    .named = true,
  },
  [sym_comma_delimited_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_delimited_sequence_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comma_delimited_sequence_repeat2] = {
    .visible = false,
    .named = false,
  },
  [anon_alias_sym_subbinary_op] = {
    .visible = true,
    .named = false,
  },
};

enum {
  field_close = 1,
  field_contents = 2,
  field_open = 3,
};

static const char *ts_field_names[] = {
  [0] = NULL,
  [field_close] = "close",
  [field_contents] = "contents",
  [field_open] = "open",
};

static const TSFieldMapSlice ts_field_map_slices[4] = {
  [1] = {.index = 0, .length = 2},
  [3] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_close, 1},
    {field_open, 0},
  [2] =
    {field_close, 2},
    {field_contents, 1},
    {field_open, 0},
};

static TSSymbol ts_alias_sequences[4][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [2] = {
    [1] = anon_alias_sym_subbinary_op,
  },
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '(') ADVANCE(20);
      if (lookahead == ')') ADVANCE(21);
      if (lookahead == '+') ADVANCE(17);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(16);
      if (lookahead == '2') ADVANCE(27);
      if (lookahead == ':') ADVANCE(15);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '>') ADVANCE(19);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(28);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('3' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 1:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(3);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '5')) ADVANCE(4);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 4:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_COLON_COLON);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_EQ_EQ_EQ);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(8);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      if (lookahead == '=') ADVANCE(7);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '>') ADVANCE(9);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead == ':') ADVANCE(6);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ':' &&
          lookahead != '<' &&
          lookahead != '=' &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ':' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(11);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(12);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '3')) ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead == ':') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_text_token1);
      if (lookahead != 0 &&
          lookahead != '(' &&
          lookahead != ')' &&
          lookahead != ',' &&
          lookahead != ':' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_time);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(2);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON_COLON] = ACTIONS(1),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [aux_sym_text_token1] = ACTIONS(1),
    [sym_time] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(63),
    [sym__expression] = STATE(5),
    [sym__nonseq_expr] = STATE(59),
    [sym_binary_op] = STATE(59),
    [sym_nonsymbol] = STATE(59),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(59),
    [sym_comma_delimited_sequence] = STATE(5),
    [sym_text] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_COLON_COLON] = ACTIONS(5),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(7),
    [anon_sym_LT_EQ_GT] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(7),
    [anon_sym_DASH_GT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_time] = ACTIONS(23),
  },
  [2] = {
    [sym__expression] = STATE(24),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(24),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(24),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(25),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(28),
    [anon_sym_LT_EQ_GT] = ACTIONS(28),
    [anon_sym_EQ_GT] = ACTIONS(28),
    [anon_sym_DASH_GT] = ACTIONS(28),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(28),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_COLON] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(34),
    [anon_sym_GT] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(40),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [aux_sym_text_token1] = ACTIONS(51),
    [sym_time] = ACTIONS(54),
  },
  [3] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(57),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(60),
    [anon_sym_LT_EQ_GT] = ACTIONS(60),
    [anon_sym_EQ_GT] = ACTIONS(60),
    [anon_sym_DASH_GT] = ACTIONS(60),
    [anon_sym_LT_EQ] = ACTIONS(63),
    [anon_sym_GT_EQ] = ACTIONS(60),
    [anon_sym_EQ_EQ] = ACTIONS(63),
    [anon_sym_EQ] = ACTIONS(63),
    [anon_sym_COLON] = ACTIONS(63),
    [anon_sym_DASH] = ACTIONS(63),
    [anon_sym_PLUS] = ACTIONS(63),
    [anon_sym_LT] = ACTIONS(66),
    [anon_sym_GT] = ACTIONS(69),
    [anon_sym_LPAREN] = ACTIONS(72),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_LBRACK] = ACTIONS(77),
    [anon_sym_RBRACK] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(80),
    [anon_sym_RBRACE] = ACTIONS(75),
    [aux_sym_text_token1] = ACTIONS(83),
    [sym_time] = ACTIONS(86),
  },
  [4] = {
    [sym__expression] = STATE(21),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(21),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(21),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_COLON_COLON] = ACTIONS(25),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(28),
    [anon_sym_LT_EQ_GT] = ACTIONS(28),
    [anon_sym_EQ_GT] = ACTIONS(28),
    [anon_sym_DASH_GT] = ACTIONS(28),
    [anon_sym_LT_EQ] = ACTIONS(31),
    [anon_sym_GT_EQ] = ACTIONS(28),
    [anon_sym_EQ_EQ] = ACTIONS(31),
    [anon_sym_EQ] = ACTIONS(31),
    [anon_sym_COLON] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(34),
    [anon_sym_GT] = ACTIONS(89),
    [anon_sym_LPAREN] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(45),
    [anon_sym_LBRACE] = ACTIONS(48),
    [anon_sym_COMMA] = ACTIONS(43),
    [aux_sym_text_token1] = ACTIONS(51),
    [sym_time] = ACTIONS(54),
  },
  [5] = {
    [sym__expression] = STATE(12),
    [sym__nonseq_expr] = STATE(59),
    [sym_binary_op] = STATE(59),
    [sym_nonsymbol] = STATE(59),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(59),
    [sym_comma_delimited_sequence] = STATE(12),
    [sym_text] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(92),
    [anon_sym_COLON_COLON] = ACTIONS(5),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(7),
    [anon_sym_LT_EQ_GT] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(7),
    [anon_sym_DASH_GT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_time] = ACTIONS(23),
  },
  [6] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(110),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [7] = {
    [sym__expression] = STATE(20),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(20),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(20),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(116),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [8] = {
    [sym__expression] = STATE(17),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(17),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(17),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(116),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [9] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(110),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [10] = {
    [sym__nonseq_expr] = STATE(10),
    [sym_binary_op] = STATE(10),
    [sym_nonsymbol] = STATE(10),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(10),
    [sym_text] = STATE(10),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(10),
    [anon_sym_COLON_COLON] = ACTIONS(118),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(121),
    [anon_sym_LT_EQ_GT] = ACTIONS(121),
    [anon_sym_EQ_GT] = ACTIONS(121),
    [anon_sym_DASH_GT] = ACTIONS(121),
    [anon_sym_LT_EQ] = ACTIONS(124),
    [anon_sym_GT_EQ] = ACTIONS(121),
    [anon_sym_EQ_EQ] = ACTIONS(124),
    [anon_sym_EQ] = ACTIONS(124),
    [anon_sym_COLON] = ACTIONS(124),
    [anon_sym_DASH] = ACTIONS(124),
    [anon_sym_PLUS] = ACTIONS(124),
    [anon_sym_LT] = ACTIONS(127),
    [anon_sym_GT] = ACTIONS(130),
    [anon_sym_LPAREN] = ACTIONS(133),
    [anon_sym_RPAREN] = ACTIONS(136),
    [anon_sym_LBRACK] = ACTIONS(138),
    [anon_sym_RBRACK] = ACTIONS(136),
    [anon_sym_LBRACE] = ACTIONS(141),
    [anon_sym_RBRACE] = ACTIONS(136),
    [anon_sym_COMMA] = ACTIONS(136),
    [aux_sym_text_token1] = ACTIONS(144),
    [sym_time] = ACTIONS(147),
  },
  [11] = {
    [sym__expression] = STATE(6),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(6),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(150),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [12] = {
    [sym__expression] = STATE(12),
    [sym__nonseq_expr] = STATE(59),
    [sym_binary_op] = STATE(59),
    [sym_nonsymbol] = STATE(59),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(59),
    [sym_comma_delimited_sequence] = STATE(12),
    [sym_text] = STATE(59),
    [aux_sym_source_file_repeat1] = STATE(12),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_COLON_COLON] = ACTIONS(152),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(155),
    [anon_sym_LT_EQ_GT] = ACTIONS(155),
    [anon_sym_EQ_GT] = ACTIONS(155),
    [anon_sym_DASH_GT] = ACTIONS(155),
    [anon_sym_LT_EQ] = ACTIONS(158),
    [anon_sym_GT_EQ] = ACTIONS(155),
    [anon_sym_EQ_EQ] = ACTIONS(158),
    [anon_sym_EQ] = ACTIONS(158),
    [anon_sym_COLON] = ACTIONS(158),
    [anon_sym_DASH] = ACTIONS(158),
    [anon_sym_PLUS] = ACTIONS(158),
    [anon_sym_LT] = ACTIONS(161),
    [anon_sym_GT] = ACTIONS(164),
    [anon_sym_LPAREN] = ACTIONS(167),
    [anon_sym_LBRACK] = ACTIONS(170),
    [anon_sym_LBRACE] = ACTIONS(173),
    [aux_sym_text_token1] = ACTIONS(176),
    [sym_time] = ACTIONS(179),
  },
  [13] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(110),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [14] = {
    [sym__expression] = STATE(19),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(19),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(19),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(116),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [15] = {
    [sym__nonseq_expr] = STATE(10),
    [sym_binary_op] = STATE(10),
    [sym_nonsymbol] = STATE(10),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(10),
    [sym_text] = STATE(10),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(10),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(182),
    [anon_sym_COMMA] = ACTIONS(182),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(184),
  },
  [16] = {
    [sym__expression] = STATE(9),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(9),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(150),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [17] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(186),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [18] = {
    [sym__expression] = STATE(13),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(13),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(13),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(150),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [19] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(186),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [20] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(186),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [21] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(188),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [22] = {
    [sym__nonseq_expr] = STATE(46),
    [sym_binary_op] = STATE(47),
    [sym_nonsymbol] = STATE(46),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(46),
    [sym_text] = STATE(46),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(190),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(190),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(190),
    [anon_sym_COMMA] = ACTIONS(190),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(192),
  },
  [23] = {
    [sym__nonseq_expr] = STATE(44),
    [sym_binary_op] = STATE(45),
    [sym_nonsymbol] = STATE(44),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(44),
    [sym_text] = STATE(44),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_RPAREN] = ACTIONS(190),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_RBRACK] = ACTIONS(190),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(190),
    [anon_sym_COMMA] = ACTIONS(190),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(194),
  },
  [24] = {
    [sym__expression] = STATE(3),
    [sym__nonseq_expr] = STATE(40),
    [sym_binary_op] = STATE(40),
    [sym_nonsymbol] = STATE(40),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(40),
    [sym_comma_delimited_sequence] = STATE(3),
    [sym_text] = STATE(40),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(28),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(196),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(114),
  },
  [25] = {
    [sym__nonseq_expr] = STATE(10),
    [sym_binary_op] = STATE(10),
    [sym_nonsymbol] = STATE(10),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(10),
    [sym_text] = STATE(10),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(10),
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(49),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_COMMA] = ACTIONS(198),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(184),
  },
  [26] = {
    [sym__nonseq_expr] = STATE(26),
    [sym_binary_op] = STATE(26),
    [sym_nonsymbol] = STATE(26),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(26),
    [sym_text] = STATE(26),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(136),
    [anon_sym_COLON_COLON] = ACTIONS(200),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(203),
    [anon_sym_LT_EQ_GT] = ACTIONS(203),
    [anon_sym_EQ_GT] = ACTIONS(203),
    [anon_sym_DASH_GT] = ACTIONS(203),
    [anon_sym_LT_EQ] = ACTIONS(206),
    [anon_sym_GT_EQ] = ACTIONS(203),
    [anon_sym_EQ_EQ] = ACTIONS(206),
    [anon_sym_EQ] = ACTIONS(206),
    [anon_sym_COLON] = ACTIONS(206),
    [anon_sym_DASH] = ACTIONS(206),
    [anon_sym_PLUS] = ACTIONS(206),
    [anon_sym_LT] = ACTIONS(209),
    [anon_sym_GT] = ACTIONS(212),
    [anon_sym_LPAREN] = ACTIONS(215),
    [anon_sym_LBRACK] = ACTIONS(218),
    [anon_sym_LBRACE] = ACTIONS(221),
    [anon_sym_COMMA] = ACTIONS(136),
    [aux_sym_text_token1] = ACTIONS(224),
    [sym_time] = ACTIONS(227),
  },
  [27] = {
    [sym__nonseq_expr] = STATE(26),
    [sym_binary_op] = STATE(26),
    [sym_nonsymbol] = STATE(26),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(26),
    [sym_text] = STATE(26),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(182),
    [anon_sym_COLON_COLON] = ACTIONS(5),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(7),
    [anon_sym_LT_EQ_GT] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(7),
    [anon_sym_DASH_GT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(182),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_time] = ACTIONS(230),
  },
  [28] = {
    [sym__nonseq_expr] = STATE(10),
    [sym_binary_op] = STATE(10),
    [sym_nonsymbol] = STATE(10),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(10),
    [sym_text] = STATE(10),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(10),
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(34),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_COMMA] = ACTIONS(232),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(184),
  },
  [29] = {
    [sym__nonseq_expr] = STATE(52),
    [sym_binary_op] = STATE(51),
    [sym_nonsymbol] = STATE(52),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(52),
    [sym_text] = STATE(52),
    [ts_builtin_sym_end] = ACTIONS(190),
    [anon_sym_COLON_COLON] = ACTIONS(5),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(7),
    [anon_sym_LT_EQ_GT] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(7),
    [anon_sym_DASH_GT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(190),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_time] = ACTIONS(234),
  },
  [30] = {
    [sym__nonseq_expr] = STATE(56),
    [sym_binary_op] = STATE(54),
    [sym_nonsymbol] = STATE(56),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(56),
    [sym_text] = STATE(56),
    [ts_builtin_sym_end] = ACTIONS(190),
    [anon_sym_COLON_COLON] = ACTIONS(5),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(7),
    [anon_sym_LT_EQ_GT] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(7),
    [anon_sym_DASH_GT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [anon_sym_COMMA] = ACTIONS(190),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_time] = ACTIONS(236),
  },
  [31] = {
    [sym__nonseq_expr] = STATE(15),
    [sym_binary_op] = STATE(15),
    [sym_nonsymbol] = STATE(15),
    [sym_symbol] = STATE(23),
    [sym_conflicting_symbol] = STATE(22),
    [sym_container] = STATE(15),
    [sym_text] = STATE(15),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(15),
    [anon_sym_COLON_COLON] = ACTIONS(94),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(96),
    [anon_sym_LT_EQ_GT] = ACTIONS(96),
    [anon_sym_EQ_GT] = ACTIONS(96),
    [anon_sym_DASH_GT] = ACTIONS(96),
    [anon_sym_LT_EQ] = ACTIONS(98),
    [anon_sym_GT_EQ] = ACTIONS(96),
    [anon_sym_EQ_EQ] = ACTIONS(98),
    [anon_sym_EQ] = ACTIONS(98),
    [anon_sym_COLON] = ACTIONS(98),
    [anon_sym_DASH] = ACTIONS(98),
    [anon_sym_PLUS] = ACTIONS(98),
    [anon_sym_LT] = ACTIONS(100),
    [anon_sym_GT] = ACTIONS(102),
    [anon_sym_LPAREN] = ACTIONS(104),
    [anon_sym_LBRACK] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [aux_sym_text_token1] = ACTIONS(112),
    [sym_time] = ACTIONS(238),
  },
  [32] = {
    [sym__nonseq_expr] = STATE(27),
    [sym_binary_op] = STATE(27),
    [sym_nonsymbol] = STATE(27),
    [sym_symbol] = STATE(30),
    [sym_conflicting_symbol] = STATE(29),
    [sym_container] = STATE(27),
    [sym_text] = STATE(27),
    [aux_sym_comma_delimited_sequence_repeat1] = STATE(27),
    [anon_sym_COLON_COLON] = ACTIONS(5),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(7),
    [anon_sym_LT_EQ_GT] = ACTIONS(7),
    [anon_sym_EQ_GT] = ACTIONS(7),
    [anon_sym_DASH_GT] = ACTIONS(7),
    [anon_sym_LT_EQ] = ACTIONS(9),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_EQ_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_COLON] = ACTIONS(9),
    [anon_sym_DASH] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(11),
    [anon_sym_GT] = ACTIONS(13),
    [anon_sym_LPAREN] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
    [aux_sym_text_token1] = ACTIONS(21),
    [sym_time] = ACTIONS(240),
  },
  [33] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(33),
    [anon_sym_COLON_COLON] = ACTIONS(182),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(182),
    [anon_sym_LT_EQ_GT] = ACTIONS(182),
    [anon_sym_EQ_GT] = ACTIONS(182),
    [anon_sym_DASH_GT] = ACTIONS(182),
    [anon_sym_LT_EQ] = ACTIONS(242),
    [anon_sym_GT_EQ] = ACTIONS(182),
    [anon_sym_EQ_EQ] = ACTIONS(242),
    [anon_sym_EQ] = ACTIONS(242),
    [anon_sym_COLON] = ACTIONS(242),
    [anon_sym_DASH] = ACTIONS(242),
    [anon_sym_PLUS] = ACTIONS(242),
    [anon_sym_LT] = ACTIONS(242),
    [anon_sym_GT] = ACTIONS(242),
    [anon_sym_LPAREN] = ACTIONS(182),
    [anon_sym_RPAREN] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(182),
    [anon_sym_RBRACK] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(182),
    [anon_sym_RBRACE] = ACTIONS(182),
    [anon_sym_COMMA] = ACTIONS(244),
    [aux_sym_text_token1] = ACTIONS(242),
    [sym_time] = ACTIONS(182),
  },
  [34] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(33),
    [anon_sym_COLON_COLON] = ACTIONS(247),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(247),
    [anon_sym_LT_EQ_GT] = ACTIONS(247),
    [anon_sym_EQ_GT] = ACTIONS(247),
    [anon_sym_DASH_GT] = ACTIONS(247),
    [anon_sym_LT_EQ] = ACTIONS(249),
    [anon_sym_GT_EQ] = ACTIONS(247),
    [anon_sym_EQ_EQ] = ACTIONS(249),
    [anon_sym_EQ] = ACTIONS(249),
    [anon_sym_COLON] = ACTIONS(249),
    [anon_sym_DASH] = ACTIONS(249),
    [anon_sym_PLUS] = ACTIONS(249),
    [anon_sym_LT] = ACTIONS(249),
    [anon_sym_GT] = ACTIONS(249),
    [anon_sym_LPAREN] = ACTIONS(247),
    [anon_sym_RPAREN] = ACTIONS(247),
    [anon_sym_LBRACK] = ACTIONS(247),
    [anon_sym_RBRACK] = ACTIONS(247),
    [anon_sym_LBRACE] = ACTIONS(247),
    [anon_sym_RBRACE] = ACTIONS(247),
    [anon_sym_COMMA] = ACTIONS(232),
    [aux_sym_text_token1] = ACTIONS(249),
    [sym_time] = ACTIONS(247),
  },
  [35] = {
    [anon_sym_COLON_COLON] = ACTIONS(251),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(251),
    [anon_sym_LT_EQ_GT] = ACTIONS(251),
    [anon_sym_EQ_GT] = ACTIONS(251),
    [anon_sym_DASH_GT] = ACTIONS(251),
    [anon_sym_LT_EQ] = ACTIONS(254),
    [anon_sym_GT_EQ] = ACTIONS(251),
    [anon_sym_EQ_EQ] = ACTIONS(254),
    [anon_sym_EQ] = ACTIONS(254),
    [anon_sym_COLON] = ACTIONS(254),
    [anon_sym_DASH] = ACTIONS(254),
    [anon_sym_PLUS] = ACTIONS(254),
    [anon_sym_LT] = ACTIONS(254),
    [anon_sym_GT] = ACTIONS(254),
    [anon_sym_LPAREN] = ACTIONS(251),
    [anon_sym_RPAREN] = ACTIONS(257),
    [anon_sym_LBRACK] = ACTIONS(251),
    [anon_sym_RBRACK] = ACTIONS(257),
    [anon_sym_LBRACE] = ACTIONS(251),
    [anon_sym_RBRACE] = ACTIONS(257),
    [anon_sym_COMMA] = ACTIONS(251),
    [aux_sym_text_token1] = ACTIONS(254),
    [sym_time] = ACTIONS(251),
  },
  [36] = {
    [anon_sym_COLON_COLON] = ACTIONS(259),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(259),
    [anon_sym_LT_EQ_GT] = ACTIONS(259),
    [anon_sym_EQ_GT] = ACTIONS(259),
    [anon_sym_DASH_GT] = ACTIONS(259),
    [anon_sym_LT_EQ] = ACTIONS(261),
    [anon_sym_GT_EQ] = ACTIONS(259),
    [anon_sym_EQ_EQ] = ACTIONS(261),
    [anon_sym_EQ] = ACTIONS(261),
    [anon_sym_COLON] = ACTIONS(261),
    [anon_sym_DASH] = ACTIONS(261),
    [anon_sym_PLUS] = ACTIONS(261),
    [anon_sym_LT] = ACTIONS(261),
    [anon_sym_GT] = ACTIONS(261),
    [anon_sym_LPAREN] = ACTIONS(259),
    [anon_sym_RPAREN] = ACTIONS(259),
    [anon_sym_LBRACK] = ACTIONS(259),
    [anon_sym_RBRACK] = ACTIONS(259),
    [anon_sym_LBRACE] = ACTIONS(259),
    [anon_sym_RBRACE] = ACTIONS(259),
    [anon_sym_COMMA] = ACTIONS(259),
    [aux_sym_text_token1] = ACTIONS(261),
    [sym_time] = ACTIONS(259),
  },
  [37] = {
    [anon_sym_COLON_COLON] = ACTIONS(263),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(263),
    [anon_sym_LT_EQ_GT] = ACTIONS(263),
    [anon_sym_EQ_GT] = ACTIONS(263),
    [anon_sym_DASH_GT] = ACTIONS(263),
    [anon_sym_LT_EQ] = ACTIONS(265),
    [anon_sym_GT_EQ] = ACTIONS(263),
    [anon_sym_EQ_EQ] = ACTIONS(265),
    [anon_sym_EQ] = ACTIONS(265),
    [anon_sym_COLON] = ACTIONS(265),
    [anon_sym_DASH] = ACTIONS(265),
    [anon_sym_PLUS] = ACTIONS(265),
    [anon_sym_LT] = ACTIONS(265),
    [anon_sym_GT] = ACTIONS(265),
    [anon_sym_LPAREN] = ACTIONS(263),
    [anon_sym_RPAREN] = ACTIONS(263),
    [anon_sym_LBRACK] = ACTIONS(263),
    [anon_sym_RBRACK] = ACTIONS(263),
    [anon_sym_LBRACE] = ACTIONS(263),
    [anon_sym_RBRACE] = ACTIONS(263),
    [anon_sym_COMMA] = ACTIONS(263),
    [aux_sym_text_token1] = ACTIONS(265),
    [sym_time] = ACTIONS(263),
  },
  [38] = {
    [anon_sym_COLON_COLON] = ACTIONS(43),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(43),
    [anon_sym_LT_EQ_GT] = ACTIONS(43),
    [anon_sym_EQ_GT] = ACTIONS(43),
    [anon_sym_DASH_GT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(267),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(267),
    [anon_sym_EQ] = ACTIONS(267),
    [anon_sym_COLON] = ACTIONS(267),
    [anon_sym_DASH] = ACTIONS(267),
    [anon_sym_PLUS] = ACTIONS(267),
    [anon_sym_LT] = ACTIONS(267),
    [anon_sym_GT] = ACTIONS(267),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_RPAREN] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_RBRACK] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [aux_sym_text_token1] = ACTIONS(267),
    [sym_time] = ACTIONS(43),
  },
  [39] = {
    [anon_sym_COLON_COLON] = ACTIONS(269),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(269),
    [anon_sym_LT_EQ_GT] = ACTIONS(269),
    [anon_sym_EQ_GT] = ACTIONS(269),
    [anon_sym_DASH_GT] = ACTIONS(269),
    [anon_sym_LT_EQ] = ACTIONS(271),
    [anon_sym_GT_EQ] = ACTIONS(269),
    [anon_sym_EQ_EQ] = ACTIONS(271),
    [anon_sym_EQ] = ACTIONS(271),
    [anon_sym_COLON] = ACTIONS(271),
    [anon_sym_DASH] = ACTIONS(271),
    [anon_sym_PLUS] = ACTIONS(271),
    [anon_sym_LT] = ACTIONS(271),
    [anon_sym_GT] = ACTIONS(271),
    [anon_sym_LPAREN] = ACTIONS(269),
    [anon_sym_RPAREN] = ACTIONS(269),
    [anon_sym_LBRACK] = ACTIONS(269),
    [anon_sym_RBRACK] = ACTIONS(269),
    [anon_sym_LBRACE] = ACTIONS(269),
    [anon_sym_RBRACE] = ACTIONS(269),
    [anon_sym_COMMA] = ACTIONS(269),
    [aux_sym_text_token1] = ACTIONS(271),
    [sym_time] = ACTIONS(269),
  },
  [40] = {
    [anon_sym_COLON_COLON] = ACTIONS(273),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(273),
    [anon_sym_LT_EQ_GT] = ACTIONS(273),
    [anon_sym_EQ_GT] = ACTIONS(273),
    [anon_sym_DASH_GT] = ACTIONS(273),
    [anon_sym_LT_EQ] = ACTIONS(275),
    [anon_sym_GT_EQ] = ACTIONS(273),
    [anon_sym_EQ_EQ] = ACTIONS(275),
    [anon_sym_EQ] = ACTIONS(275),
    [anon_sym_COLON] = ACTIONS(275),
    [anon_sym_DASH] = ACTIONS(275),
    [anon_sym_PLUS] = ACTIONS(275),
    [anon_sym_LT] = ACTIONS(275),
    [anon_sym_GT] = ACTIONS(275),
    [anon_sym_LPAREN] = ACTIONS(273),
    [anon_sym_RPAREN] = ACTIONS(273),
    [anon_sym_LBRACK] = ACTIONS(273),
    [anon_sym_RBRACK] = ACTIONS(273),
    [anon_sym_LBRACE] = ACTIONS(273),
    [anon_sym_RBRACE] = ACTIONS(273),
    [anon_sym_COMMA] = ACTIONS(277),
    [aux_sym_text_token1] = ACTIONS(275),
    [sym_time] = ACTIONS(273),
  },
  [41] = {
    [anon_sym_COLON_COLON] = ACTIONS(257),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(257),
    [anon_sym_LT_EQ_GT] = ACTIONS(257),
    [anon_sym_EQ_GT] = ACTIONS(257),
    [anon_sym_DASH_GT] = ACTIONS(257),
    [anon_sym_LT_EQ] = ACTIONS(279),
    [anon_sym_GT_EQ] = ACTIONS(257),
    [anon_sym_EQ_EQ] = ACTIONS(279),
    [anon_sym_EQ] = ACTIONS(279),
    [anon_sym_COLON] = ACTIONS(279),
    [anon_sym_DASH] = ACTIONS(279),
    [anon_sym_PLUS] = ACTIONS(279),
    [anon_sym_LT] = ACTIONS(279),
    [anon_sym_GT] = ACTIONS(279),
    [anon_sym_LPAREN] = ACTIONS(257),
    [anon_sym_RPAREN] = ACTIONS(257),
    [anon_sym_LBRACK] = ACTIONS(257),
    [anon_sym_RBRACK] = ACTIONS(257),
    [anon_sym_LBRACE] = ACTIONS(257),
    [anon_sym_RBRACE] = ACTIONS(257),
    [anon_sym_COMMA] = ACTIONS(257),
    [aux_sym_text_token1] = ACTIONS(279),
    [sym_time] = ACTIONS(257),
  },
  [42] = {
    [anon_sym_COLON_COLON] = ACTIONS(281),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(281),
    [anon_sym_LT_EQ_GT] = ACTIONS(281),
    [anon_sym_EQ_GT] = ACTIONS(281),
    [anon_sym_DASH_GT] = ACTIONS(281),
    [anon_sym_LT_EQ] = ACTIONS(284),
    [anon_sym_GT_EQ] = ACTIONS(281),
    [anon_sym_EQ_EQ] = ACTIONS(284),
    [anon_sym_EQ] = ACTIONS(284),
    [anon_sym_COLON] = ACTIONS(284),
    [anon_sym_DASH] = ACTIONS(284),
    [anon_sym_PLUS] = ACTIONS(284),
    [anon_sym_LT] = ACTIONS(284),
    [anon_sym_GT] = ACTIONS(284),
    [anon_sym_LPAREN] = ACTIONS(281),
    [anon_sym_RPAREN] = ACTIONS(287),
    [anon_sym_LBRACK] = ACTIONS(281),
    [anon_sym_RBRACK] = ACTIONS(287),
    [anon_sym_LBRACE] = ACTIONS(281),
    [anon_sym_RBRACE] = ACTIONS(287),
    [anon_sym_COMMA] = ACTIONS(281),
    [aux_sym_text_token1] = ACTIONS(284),
    [sym_time] = ACTIONS(281),
  },
  [43] = {
    [anon_sym_COLON_COLON] = ACTIONS(287),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(287),
    [anon_sym_LT_EQ_GT] = ACTIONS(287),
    [anon_sym_EQ_GT] = ACTIONS(287),
    [anon_sym_DASH_GT] = ACTIONS(287),
    [anon_sym_LT_EQ] = ACTIONS(289),
    [anon_sym_GT_EQ] = ACTIONS(287),
    [anon_sym_EQ_EQ] = ACTIONS(289),
    [anon_sym_EQ] = ACTIONS(289),
    [anon_sym_COLON] = ACTIONS(289),
    [anon_sym_DASH] = ACTIONS(289),
    [anon_sym_PLUS] = ACTIONS(289),
    [anon_sym_LT] = ACTIONS(289),
    [anon_sym_GT] = ACTIONS(289),
    [anon_sym_LPAREN] = ACTIONS(287),
    [anon_sym_RPAREN] = ACTIONS(287),
    [anon_sym_LBRACK] = ACTIONS(287),
    [anon_sym_RBRACK] = ACTIONS(287),
    [anon_sym_LBRACE] = ACTIONS(287),
    [anon_sym_RBRACE] = ACTIONS(287),
    [anon_sym_COMMA] = ACTIONS(287),
    [aux_sym_text_token1] = ACTIONS(289),
    [sym_time] = ACTIONS(287),
  },
  [44] = {
    [anon_sym_COLON_COLON] = ACTIONS(291),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(291),
    [anon_sym_LT_EQ_GT] = ACTIONS(291),
    [anon_sym_EQ_GT] = ACTIONS(291),
    [anon_sym_DASH_GT] = ACTIONS(291),
    [anon_sym_LT_EQ] = ACTIONS(293),
    [anon_sym_GT_EQ] = ACTIONS(291),
    [anon_sym_EQ_EQ] = ACTIONS(293),
    [anon_sym_EQ] = ACTIONS(293),
    [anon_sym_COLON] = ACTIONS(293),
    [anon_sym_DASH] = ACTIONS(293),
    [anon_sym_PLUS] = ACTIONS(293),
    [anon_sym_LT] = ACTIONS(293),
    [anon_sym_GT] = ACTIONS(293),
    [anon_sym_LPAREN] = ACTIONS(291),
    [anon_sym_RPAREN] = ACTIONS(291),
    [anon_sym_LBRACK] = ACTIONS(291),
    [anon_sym_RBRACK] = ACTIONS(291),
    [anon_sym_LBRACE] = ACTIONS(291),
    [anon_sym_RBRACE] = ACTIONS(291),
    [anon_sym_COMMA] = ACTIONS(291),
    [aux_sym_text_token1] = ACTIONS(293),
    [sym_time] = ACTIONS(291),
  },
  [45] = {
    [anon_sym_COLON_COLON] = ACTIONS(295),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(295),
    [anon_sym_LT_EQ_GT] = ACTIONS(295),
    [anon_sym_EQ_GT] = ACTIONS(295),
    [anon_sym_DASH_GT] = ACTIONS(295),
    [anon_sym_LT_EQ] = ACTIONS(297),
    [anon_sym_GT_EQ] = ACTIONS(295),
    [anon_sym_EQ_EQ] = ACTIONS(297),
    [anon_sym_EQ] = ACTIONS(297),
    [anon_sym_COLON] = ACTIONS(297),
    [anon_sym_DASH] = ACTIONS(297),
    [anon_sym_PLUS] = ACTIONS(297),
    [anon_sym_LT] = ACTIONS(297),
    [anon_sym_GT] = ACTIONS(297),
    [anon_sym_LPAREN] = ACTIONS(295),
    [anon_sym_RPAREN] = ACTIONS(295),
    [anon_sym_LBRACK] = ACTIONS(295),
    [anon_sym_RBRACK] = ACTIONS(295),
    [anon_sym_LBRACE] = ACTIONS(295),
    [anon_sym_RBRACE] = ACTIONS(295),
    [anon_sym_COMMA] = ACTIONS(295),
    [aux_sym_text_token1] = ACTIONS(297),
    [sym_time] = ACTIONS(295),
  },
  [46] = {
    [anon_sym_COLON_COLON] = ACTIONS(291),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(291),
    [anon_sym_LT_EQ_GT] = ACTIONS(291),
    [anon_sym_EQ_GT] = ACTIONS(291),
    [anon_sym_DASH_GT] = ACTIONS(291),
    [anon_sym_LT_EQ] = ACTIONS(293),
    [anon_sym_GT_EQ] = ACTIONS(291),
    [anon_sym_EQ_EQ] = ACTIONS(293),
    [anon_sym_EQ] = ACTIONS(293),
    [anon_sym_COLON] = ACTIONS(293),
    [anon_sym_DASH] = ACTIONS(293),
    [anon_sym_PLUS] = ACTIONS(293),
    [anon_sym_LT] = ACTIONS(293),
    [anon_sym_GT] = ACTIONS(293),
    [anon_sym_LPAREN] = ACTIONS(291),
    [anon_sym_RPAREN] = ACTIONS(291),
    [anon_sym_LBRACK] = ACTIONS(291),
    [anon_sym_RBRACK] = ACTIONS(291),
    [anon_sym_LBRACE] = ACTIONS(291),
    [anon_sym_RBRACE] = ACTIONS(291),
    [anon_sym_COMMA] = ACTIONS(291),
    [aux_sym_text_token1] = ACTIONS(293),
    [sym_time] = ACTIONS(291),
  },
  [47] = {
    [anon_sym_COLON_COLON] = ACTIONS(295),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(295),
    [anon_sym_LT_EQ_GT] = ACTIONS(295),
    [anon_sym_EQ_GT] = ACTIONS(295),
    [anon_sym_DASH_GT] = ACTIONS(295),
    [anon_sym_LT_EQ] = ACTIONS(297),
    [anon_sym_GT_EQ] = ACTIONS(295),
    [anon_sym_EQ_EQ] = ACTIONS(297),
    [anon_sym_EQ] = ACTIONS(297),
    [anon_sym_COLON] = ACTIONS(297),
    [anon_sym_DASH] = ACTIONS(297),
    [anon_sym_PLUS] = ACTIONS(297),
    [anon_sym_LT] = ACTIONS(297),
    [anon_sym_GT] = ACTIONS(297),
    [anon_sym_LPAREN] = ACTIONS(295),
    [anon_sym_RPAREN] = ACTIONS(295),
    [anon_sym_LBRACK] = ACTIONS(295),
    [anon_sym_RBRACK] = ACTIONS(295),
    [anon_sym_LBRACE] = ACTIONS(295),
    [anon_sym_RBRACE] = ACTIONS(295),
    [anon_sym_COMMA] = ACTIONS(295),
    [aux_sym_text_token1] = ACTIONS(297),
    [sym_time] = ACTIONS(295),
  },
  [48] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(182),
    [anon_sym_COLON_COLON] = ACTIONS(182),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(182),
    [anon_sym_LT_EQ_GT] = ACTIONS(182),
    [anon_sym_EQ_GT] = ACTIONS(182),
    [anon_sym_DASH_GT] = ACTIONS(182),
    [anon_sym_LT_EQ] = ACTIONS(242),
    [anon_sym_GT_EQ] = ACTIONS(182),
    [anon_sym_EQ_EQ] = ACTIONS(242),
    [anon_sym_EQ] = ACTIONS(242),
    [anon_sym_COLON] = ACTIONS(242),
    [anon_sym_DASH] = ACTIONS(242),
    [anon_sym_PLUS] = ACTIONS(242),
    [anon_sym_LT] = ACTIONS(242),
    [anon_sym_GT] = ACTIONS(242),
    [anon_sym_LPAREN] = ACTIONS(182),
    [anon_sym_LBRACK] = ACTIONS(182),
    [anon_sym_LBRACE] = ACTIONS(182),
    [anon_sym_COMMA] = ACTIONS(299),
    [aux_sym_text_token1] = ACTIONS(242),
    [sym_time] = ACTIONS(182),
  },
  [49] = {
    [aux_sym_comma_delimited_sequence_repeat2] = STATE(48),
    [ts_builtin_sym_end] = ACTIONS(247),
    [anon_sym_COLON_COLON] = ACTIONS(247),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(247),
    [anon_sym_LT_EQ_GT] = ACTIONS(247),
    [anon_sym_EQ_GT] = ACTIONS(247),
    [anon_sym_DASH_GT] = ACTIONS(247),
    [anon_sym_LT_EQ] = ACTIONS(249),
    [anon_sym_GT_EQ] = ACTIONS(247),
    [anon_sym_EQ_EQ] = ACTIONS(249),
    [anon_sym_EQ] = ACTIONS(249),
    [anon_sym_COLON] = ACTIONS(249),
    [anon_sym_DASH] = ACTIONS(249),
    [anon_sym_PLUS] = ACTIONS(249),
    [anon_sym_LT] = ACTIONS(249),
    [anon_sym_GT] = ACTIONS(249),
    [anon_sym_LPAREN] = ACTIONS(247),
    [anon_sym_LBRACK] = ACTIONS(247),
    [anon_sym_LBRACE] = ACTIONS(247),
    [anon_sym_COMMA] = ACTIONS(198),
    [aux_sym_text_token1] = ACTIONS(249),
    [sym_time] = ACTIONS(247),
  },
  [50] = {
    [ts_builtin_sym_end] = ACTIONS(257),
    [anon_sym_COLON_COLON] = ACTIONS(251),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(251),
    [anon_sym_LT_EQ_GT] = ACTIONS(251),
    [anon_sym_EQ_GT] = ACTIONS(251),
    [anon_sym_DASH_GT] = ACTIONS(251),
    [anon_sym_LT_EQ] = ACTIONS(254),
    [anon_sym_GT_EQ] = ACTIONS(251),
    [anon_sym_EQ_EQ] = ACTIONS(254),
    [anon_sym_EQ] = ACTIONS(254),
    [anon_sym_COLON] = ACTIONS(254),
    [anon_sym_DASH] = ACTIONS(254),
    [anon_sym_PLUS] = ACTIONS(254),
    [anon_sym_LT] = ACTIONS(254),
    [anon_sym_GT] = ACTIONS(254),
    [anon_sym_LPAREN] = ACTIONS(251),
    [anon_sym_LBRACK] = ACTIONS(251),
    [anon_sym_LBRACE] = ACTIONS(251),
    [anon_sym_COMMA] = ACTIONS(251),
    [aux_sym_text_token1] = ACTIONS(254),
    [sym_time] = ACTIONS(251),
  },
  [51] = {
    [ts_builtin_sym_end] = ACTIONS(295),
    [anon_sym_COLON_COLON] = ACTIONS(295),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(295),
    [anon_sym_LT_EQ_GT] = ACTIONS(295),
    [anon_sym_EQ_GT] = ACTIONS(295),
    [anon_sym_DASH_GT] = ACTIONS(295),
    [anon_sym_LT_EQ] = ACTIONS(297),
    [anon_sym_GT_EQ] = ACTIONS(295),
    [anon_sym_EQ_EQ] = ACTIONS(297),
    [anon_sym_EQ] = ACTIONS(297),
    [anon_sym_COLON] = ACTIONS(297),
    [anon_sym_DASH] = ACTIONS(297),
    [anon_sym_PLUS] = ACTIONS(297),
    [anon_sym_LT] = ACTIONS(297),
    [anon_sym_GT] = ACTIONS(297),
    [anon_sym_LPAREN] = ACTIONS(295),
    [anon_sym_LBRACK] = ACTIONS(295),
    [anon_sym_LBRACE] = ACTIONS(295),
    [anon_sym_COMMA] = ACTIONS(295),
    [aux_sym_text_token1] = ACTIONS(297),
    [sym_time] = ACTIONS(295),
  },
  [52] = {
    [ts_builtin_sym_end] = ACTIONS(291),
    [anon_sym_COLON_COLON] = ACTIONS(291),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(291),
    [anon_sym_LT_EQ_GT] = ACTIONS(291),
    [anon_sym_EQ_GT] = ACTIONS(291),
    [anon_sym_DASH_GT] = ACTIONS(291),
    [anon_sym_LT_EQ] = ACTIONS(293),
    [anon_sym_GT_EQ] = ACTIONS(291),
    [anon_sym_EQ_EQ] = ACTIONS(293),
    [anon_sym_EQ] = ACTIONS(293),
    [anon_sym_COLON] = ACTIONS(293),
    [anon_sym_DASH] = ACTIONS(293),
    [anon_sym_PLUS] = ACTIONS(293),
    [anon_sym_LT] = ACTIONS(293),
    [anon_sym_GT] = ACTIONS(293),
    [anon_sym_LPAREN] = ACTIONS(291),
    [anon_sym_LBRACK] = ACTIONS(291),
    [anon_sym_LBRACE] = ACTIONS(291),
    [anon_sym_COMMA] = ACTIONS(291),
    [aux_sym_text_token1] = ACTIONS(293),
    [sym_time] = ACTIONS(291),
  },
  [53] = {
    [ts_builtin_sym_end] = ACTIONS(259),
    [anon_sym_COLON_COLON] = ACTIONS(259),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(259),
    [anon_sym_LT_EQ_GT] = ACTIONS(259),
    [anon_sym_EQ_GT] = ACTIONS(259),
    [anon_sym_DASH_GT] = ACTIONS(259),
    [anon_sym_LT_EQ] = ACTIONS(261),
    [anon_sym_GT_EQ] = ACTIONS(259),
    [anon_sym_EQ_EQ] = ACTIONS(261),
    [anon_sym_EQ] = ACTIONS(261),
    [anon_sym_COLON] = ACTIONS(261),
    [anon_sym_DASH] = ACTIONS(261),
    [anon_sym_PLUS] = ACTIONS(261),
    [anon_sym_LT] = ACTIONS(261),
    [anon_sym_GT] = ACTIONS(261),
    [anon_sym_LPAREN] = ACTIONS(259),
    [anon_sym_LBRACK] = ACTIONS(259),
    [anon_sym_LBRACE] = ACTIONS(259),
    [anon_sym_COMMA] = ACTIONS(259),
    [aux_sym_text_token1] = ACTIONS(261),
    [sym_time] = ACTIONS(259),
  },
  [54] = {
    [ts_builtin_sym_end] = ACTIONS(295),
    [anon_sym_COLON_COLON] = ACTIONS(295),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(295),
    [anon_sym_LT_EQ_GT] = ACTIONS(295),
    [anon_sym_EQ_GT] = ACTIONS(295),
    [anon_sym_DASH_GT] = ACTIONS(295),
    [anon_sym_LT_EQ] = ACTIONS(297),
    [anon_sym_GT_EQ] = ACTIONS(295),
    [anon_sym_EQ_EQ] = ACTIONS(297),
    [anon_sym_EQ] = ACTIONS(297),
    [anon_sym_COLON] = ACTIONS(297),
    [anon_sym_DASH] = ACTIONS(297),
    [anon_sym_PLUS] = ACTIONS(297),
    [anon_sym_LT] = ACTIONS(297),
    [anon_sym_GT] = ACTIONS(297),
    [anon_sym_LPAREN] = ACTIONS(295),
    [anon_sym_LBRACK] = ACTIONS(295),
    [anon_sym_LBRACE] = ACTIONS(295),
    [anon_sym_COMMA] = ACTIONS(295),
    [aux_sym_text_token1] = ACTIONS(297),
    [sym_time] = ACTIONS(295),
  },
  [55] = {
    [ts_builtin_sym_end] = ACTIONS(257),
    [anon_sym_COLON_COLON] = ACTIONS(257),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(257),
    [anon_sym_LT_EQ_GT] = ACTIONS(257),
    [anon_sym_EQ_GT] = ACTIONS(257),
    [anon_sym_DASH_GT] = ACTIONS(257),
    [anon_sym_LT_EQ] = ACTIONS(279),
    [anon_sym_GT_EQ] = ACTIONS(257),
    [anon_sym_EQ_EQ] = ACTIONS(279),
    [anon_sym_EQ] = ACTIONS(279),
    [anon_sym_COLON] = ACTIONS(279),
    [anon_sym_DASH] = ACTIONS(279),
    [anon_sym_PLUS] = ACTIONS(279),
    [anon_sym_LT] = ACTIONS(279),
    [anon_sym_GT] = ACTIONS(279),
    [anon_sym_LPAREN] = ACTIONS(257),
    [anon_sym_LBRACK] = ACTIONS(257),
    [anon_sym_LBRACE] = ACTIONS(257),
    [anon_sym_COMMA] = ACTIONS(257),
    [aux_sym_text_token1] = ACTIONS(279),
    [sym_time] = ACTIONS(257),
  },
  [56] = {
    [ts_builtin_sym_end] = ACTIONS(291),
    [anon_sym_COLON_COLON] = ACTIONS(291),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(291),
    [anon_sym_LT_EQ_GT] = ACTIONS(291),
    [anon_sym_EQ_GT] = ACTIONS(291),
    [anon_sym_DASH_GT] = ACTIONS(291),
    [anon_sym_LT_EQ] = ACTIONS(293),
    [anon_sym_GT_EQ] = ACTIONS(291),
    [anon_sym_EQ_EQ] = ACTIONS(293),
    [anon_sym_EQ] = ACTIONS(293),
    [anon_sym_COLON] = ACTIONS(293),
    [anon_sym_DASH] = ACTIONS(293),
    [anon_sym_PLUS] = ACTIONS(293),
    [anon_sym_LT] = ACTIONS(293),
    [anon_sym_GT] = ACTIONS(293),
    [anon_sym_LPAREN] = ACTIONS(291),
    [anon_sym_LBRACK] = ACTIONS(291),
    [anon_sym_LBRACE] = ACTIONS(291),
    [anon_sym_COMMA] = ACTIONS(291),
    [aux_sym_text_token1] = ACTIONS(293),
    [sym_time] = ACTIONS(291),
  },
  [57] = {
    [ts_builtin_sym_end] = ACTIONS(287),
    [anon_sym_COLON_COLON] = ACTIONS(287),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(287),
    [anon_sym_LT_EQ_GT] = ACTIONS(287),
    [anon_sym_EQ_GT] = ACTIONS(287),
    [anon_sym_DASH_GT] = ACTIONS(287),
    [anon_sym_LT_EQ] = ACTIONS(289),
    [anon_sym_GT_EQ] = ACTIONS(287),
    [anon_sym_EQ_EQ] = ACTIONS(289),
    [anon_sym_EQ] = ACTIONS(289),
    [anon_sym_COLON] = ACTIONS(289),
    [anon_sym_DASH] = ACTIONS(289),
    [anon_sym_PLUS] = ACTIONS(289),
    [anon_sym_LT] = ACTIONS(289),
    [anon_sym_GT] = ACTIONS(289),
    [anon_sym_LPAREN] = ACTIONS(287),
    [anon_sym_LBRACK] = ACTIONS(287),
    [anon_sym_LBRACE] = ACTIONS(287),
    [anon_sym_COMMA] = ACTIONS(287),
    [aux_sym_text_token1] = ACTIONS(289),
    [sym_time] = ACTIONS(287),
  },
  [58] = {
    [ts_builtin_sym_end] = ACTIONS(287),
    [anon_sym_COLON_COLON] = ACTIONS(281),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(281),
    [anon_sym_LT_EQ_GT] = ACTIONS(281),
    [anon_sym_EQ_GT] = ACTIONS(281),
    [anon_sym_DASH_GT] = ACTIONS(281),
    [anon_sym_LT_EQ] = ACTIONS(284),
    [anon_sym_GT_EQ] = ACTIONS(281),
    [anon_sym_EQ_EQ] = ACTIONS(284),
    [anon_sym_EQ] = ACTIONS(284),
    [anon_sym_COLON] = ACTIONS(284),
    [anon_sym_DASH] = ACTIONS(284),
    [anon_sym_PLUS] = ACTIONS(284),
    [anon_sym_LT] = ACTIONS(284),
    [anon_sym_GT] = ACTIONS(284),
    [anon_sym_LPAREN] = ACTIONS(281),
    [anon_sym_LBRACK] = ACTIONS(281),
    [anon_sym_LBRACE] = ACTIONS(281),
    [anon_sym_COMMA] = ACTIONS(281),
    [aux_sym_text_token1] = ACTIONS(284),
    [sym_time] = ACTIONS(281),
  },
  [59] = {
    [ts_builtin_sym_end] = ACTIONS(273),
    [anon_sym_COLON_COLON] = ACTIONS(273),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(273),
    [anon_sym_LT_EQ_GT] = ACTIONS(273),
    [anon_sym_EQ_GT] = ACTIONS(273),
    [anon_sym_DASH_GT] = ACTIONS(273),
    [anon_sym_LT_EQ] = ACTIONS(275),
    [anon_sym_GT_EQ] = ACTIONS(273),
    [anon_sym_EQ_EQ] = ACTIONS(275),
    [anon_sym_EQ] = ACTIONS(275),
    [anon_sym_COLON] = ACTIONS(275),
    [anon_sym_DASH] = ACTIONS(275),
    [anon_sym_PLUS] = ACTIONS(275),
    [anon_sym_LT] = ACTIONS(275),
    [anon_sym_GT] = ACTIONS(275),
    [anon_sym_LPAREN] = ACTIONS(273),
    [anon_sym_LBRACK] = ACTIONS(273),
    [anon_sym_LBRACE] = ACTIONS(273),
    [anon_sym_COMMA] = ACTIONS(277),
    [aux_sym_text_token1] = ACTIONS(275),
    [sym_time] = ACTIONS(273),
  },
  [60] = {
    [ts_builtin_sym_end] = ACTIONS(269),
    [anon_sym_COLON_COLON] = ACTIONS(269),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(269),
    [anon_sym_LT_EQ_GT] = ACTIONS(269),
    [anon_sym_EQ_GT] = ACTIONS(269),
    [anon_sym_DASH_GT] = ACTIONS(269),
    [anon_sym_LT_EQ] = ACTIONS(271),
    [anon_sym_GT_EQ] = ACTIONS(269),
    [anon_sym_EQ_EQ] = ACTIONS(271),
    [anon_sym_EQ] = ACTIONS(271),
    [anon_sym_COLON] = ACTIONS(271),
    [anon_sym_DASH] = ACTIONS(271),
    [anon_sym_PLUS] = ACTIONS(271),
    [anon_sym_LT] = ACTIONS(271),
    [anon_sym_GT] = ACTIONS(271),
    [anon_sym_LPAREN] = ACTIONS(269),
    [anon_sym_LBRACK] = ACTIONS(269),
    [anon_sym_LBRACE] = ACTIONS(269),
    [anon_sym_COMMA] = ACTIONS(269),
    [aux_sym_text_token1] = ACTIONS(271),
    [sym_time] = ACTIONS(269),
  },
  [61] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_COLON_COLON] = ACTIONS(43),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(43),
    [anon_sym_LT_EQ_GT] = ACTIONS(43),
    [anon_sym_EQ_GT] = ACTIONS(43),
    [anon_sym_DASH_GT] = ACTIONS(43),
    [anon_sym_LT_EQ] = ACTIONS(267),
    [anon_sym_GT_EQ] = ACTIONS(43),
    [anon_sym_EQ_EQ] = ACTIONS(267),
    [anon_sym_EQ] = ACTIONS(267),
    [anon_sym_COLON] = ACTIONS(267),
    [anon_sym_DASH] = ACTIONS(267),
    [anon_sym_PLUS] = ACTIONS(267),
    [anon_sym_LT] = ACTIONS(267),
    [anon_sym_GT] = ACTIONS(267),
    [anon_sym_LPAREN] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(43),
    [anon_sym_LBRACE] = ACTIONS(43),
    [anon_sym_COMMA] = ACTIONS(43),
    [aux_sym_text_token1] = ACTIONS(267),
    [sym_time] = ACTIONS(43),
  },
  [62] = {
    [ts_builtin_sym_end] = ACTIONS(263),
    [anon_sym_COLON_COLON] = ACTIONS(263),
    [anon_sym_EQ_EQ_EQ] = ACTIONS(263),
    [anon_sym_LT_EQ_GT] = ACTIONS(263),
    [anon_sym_EQ_GT] = ACTIONS(263),
    [anon_sym_DASH_GT] = ACTIONS(263),
    [anon_sym_LT_EQ] = ACTIONS(265),
    [anon_sym_GT_EQ] = ACTIONS(263),
    [anon_sym_EQ_EQ] = ACTIONS(265),
    [anon_sym_EQ] = ACTIONS(265),
    [anon_sym_COLON] = ACTIONS(265),
    [anon_sym_DASH] = ACTIONS(265),
    [anon_sym_PLUS] = ACTIONS(265),
    [anon_sym_LT] = ACTIONS(265),
    [anon_sym_GT] = ACTIONS(265),
    [anon_sym_LPAREN] = ACTIONS(263),
    [anon_sym_LBRACK] = ACTIONS(263),
    [anon_sym_LBRACE] = ACTIONS(263),
    [anon_sym_COMMA] = ACTIONS(263),
    [aux_sym_text_token1] = ACTIONS(265),
    [sym_time] = ACTIONS(263),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(302), 1,
      ts_builtin_sym_end,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(63)] = 0,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 0),
  [5] = {.count = 1, .reusable = true}, SHIFT(53),
  [7] = {.count = 1, .reusable = true}, SHIFT(62),
  [9] = {.count = 1, .reusable = false}, SHIFT(62),
  [11] = {.count = 1, .reusable = false}, SHIFT(4),
  [13] = {.count = 1, .reusable = false}, SHIFT(61),
  [15] = {.count = 1, .reusable = true}, SHIFT(14),
  [17] = {.count = 1, .reusable = true}, SHIFT(7),
  [19] = {.count = 1, .reusable = true}, SHIFT(8),
  [21] = {.count = 1, .reusable = false}, SHIFT(60),
  [23] = {.count = 1, .reusable = true}, SHIFT(59),
  [25] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), SHIFT(36),
  [28] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), SHIFT(37),
  [31] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), SHIFT(37),
  [34] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), SHIFT(2),
  [37] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), SHIFT(42),
  [40] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), SHIFT(18),
  [43] = {.count = 1, .reusable = true}, REDUCE(sym_conflicting_symbol, 1),
  [45] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), SHIFT(16),
  [48] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), SHIFT(11),
  [51] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), SHIFT(39),
  [54] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), SHIFT(40),
  [57] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(36),
  [60] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [63] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(37),
  [66] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(2),
  [69] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [72] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [75] = {.count = 1, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2),
  [77] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(16),
  [80] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [83] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [86] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(40),
  [89] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), SHIFT(58),
  [92] = {.count = 1, .reusable = true}, REDUCE(sym_source_file, 1),
  [94] = {.count = 1, .reusable = true}, SHIFT(36),
  [96] = {.count = 1, .reusable = true}, SHIFT(37),
  [98] = {.count = 1, .reusable = false}, SHIFT(37),
  [100] = {.count = 1, .reusable = false}, SHIFT(2),
  [102] = {.count = 1, .reusable = false}, SHIFT(38),
  [104] = {.count = 1, .reusable = true}, SHIFT(18),
  [106] = {.count = 1, .reusable = true}, SHIFT(16),
  [108] = {.count = 1, .reusable = true}, SHIFT(11),
  [110] = {.count = 1, .reusable = true}, SHIFT(41),
  [112] = {.count = 1, .reusable = false}, SHIFT(39),
  [114] = {.count = 1, .reusable = true}, SHIFT(40),
  [116] = {.count = 1, .reusable = true}, SHIFT(57),
  [118] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(36),
  [121] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(37),
  [124] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(37),
  [127] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(2),
  [130] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(38),
  [133] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(18),
  [136] = {.count = 1, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2),
  [138] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(16),
  [141] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(11),
  [144] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(39),
  [147] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(10),
  [150] = {.count = 1, .reusable = true}, SHIFT(43),
  [152] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(53),
  [155] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [158] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(62),
  [161] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [164] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [167] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [170] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [173] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [176] = {.count = 2, .reusable = false}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(60),
  [179] = {.count = 2, .reusable = true}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(59),
  [182] = {.count = 1, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2),
  [184] = {.count = 1, .reusable = true}, SHIFT(10),
  [186] = {.count = 1, .reusable = true}, SHIFT(55),
  [188] = {.count = 1, .reusable = false}, SHIFT(50),
  [190] = {.count = 1, .reusable = true}, REDUCE(sym__nonseq_expr, 1),
  [192] = {.count = 1, .reusable = true}, SHIFT(46),
  [194] = {.count = 1, .reusable = true}, SHIFT(44),
  [196] = {.count = 1, .reusable = false}, SHIFT(35),
  [198] = {.count = 1, .reusable = true}, SHIFT(32),
  [200] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(53),
  [203] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(62),
  [206] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(62),
  [209] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(4),
  [212] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(61),
  [215] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(14),
  [218] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(7),
  [221] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(8),
  [224] = {.count = 2, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(60),
  [227] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 2), SHIFT_REPEAT(26),
  [230] = {.count = 1, .reusable = true}, SHIFT(26),
  [232] = {.count = 1, .reusable = true}, SHIFT(31),
  [234] = {.count = 1, .reusable = true}, SHIFT(52),
  [236] = {.count = 1, .reusable = true}, SHIFT(56),
  [238] = {.count = 1, .reusable = true}, SHIFT(15),
  [240] = {.count = 1, .reusable = true}, SHIFT(27),
  [242] = {.count = 1, .reusable = false}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2),
  [244] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2), SHIFT_REPEAT(31),
  [247] = {.count = 1, .reusable = true}, REDUCE(sym_comma_delimited_sequence, 2),
  [249] = {.count = 1, .reusable = false}, REDUCE(sym_comma_delimited_sequence, 2),
  [251] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), REDUCE(sym_container, 3, .production_id = 3),
  [254] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), REDUCE(sym_container, 3, .production_id = 3),
  [257] = {.count = 1, .reusable = true}, REDUCE(sym_container, 3, .production_id = 3),
  [259] = {.count = 1, .reusable = true}, REDUCE(sym_nonsymbol, 1),
  [261] = {.count = 1, .reusable = false}, REDUCE(sym_nonsymbol, 1),
  [263] = {.count = 1, .reusable = true}, REDUCE(sym_symbol, 1),
  [265] = {.count = 1, .reusable = false}, REDUCE(sym_symbol, 1),
  [267] = {.count = 1, .reusable = false}, REDUCE(sym_conflicting_symbol, 1),
  [269] = {.count = 1, .reusable = true}, REDUCE(sym_text, 1),
  [271] = {.count = 1, .reusable = false}, REDUCE(sym_text, 1),
  [273] = {.count = 1, .reusable = true}, REDUCE(sym__expression, 1),
  [275] = {.count = 1, .reusable = false}, REDUCE(sym__expression, 1),
  [277] = {.count = 1, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat1, 1),
  [279] = {.count = 1, .reusable = false}, REDUCE(sym_container, 3, .production_id = 3),
  [281] = {.count = 2, .reusable = true}, REDUCE(sym_conflicting_symbol, 1), REDUCE(sym_container, 2, .production_id = 1),
  [284] = {.count = 2, .reusable = false}, REDUCE(sym_conflicting_symbol, 1), REDUCE(sym_container, 2, .production_id = 1),
  [287] = {.count = 1, .reusable = true}, REDUCE(sym_container, 2, .production_id = 1),
  [289] = {.count = 1, .reusable = false}, REDUCE(sym_container, 2, .production_id = 1),
  [291] = {.count = 1, .reusable = true}, REDUCE(sym_binary_op, 2),
  [293] = {.count = 1, .reusable = false}, REDUCE(sym_binary_op, 2),
  [295] = {.count = 1, .reusable = true}, REDUCE(sym_binary_op, 2, .production_id = 2),
  [297] = {.count = 1, .reusable = false}, REDUCE(sym_binary_op, 2, .production_id = 2),
  [299] = {.count = 2, .reusable = true}, REDUCE(aux_sym_comma_delimited_sequence_repeat2, 2), SHIFT_REPEAT(32),
  [302] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_sillyfmt(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .field_names = ts_field_names,
    .field_map_slices = (const TSFieldMapSlice *)ts_field_map_slices,
    .field_map_entries = (const TSFieldMapEntry *)ts_field_map_entries,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
