[package]
name = "sillyfmt-wasm"
version = "0.1.0"
authors = ["Robert Ying <robertying@stripe.com>"]
edition = "2018"

[dependencies]
sillyfmt = { path = "../sillyfmt" }
stdweb = "0.4"
serde = { version = "1.0", features = ["derive"] }
